### ISSUE TITLE
Scatter: Errs when no data points are returned

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1006]
<img width="1141" alt="Screen Shot 2022-03-30 at 5 43 27 PM" src="https://user-images.githubusercontent.com/11710234/160936237-f1f13427-47cc-4192-af78-926ff3cb0c80.png">

Took this screenshot _right_ before the error covered the screen 🙂  Looks like the scatterplot response has `scatterplot.data` as an empty array. `sampleSizeTable` is also an empty array. 

Would the front end prefer an empty array be returned in this case? Or something else like null?

**Comment by moontrip** [comment]
@asizemore I think that perhaps this can be handled at the front end. Will test this later.

**Comment by SheenaTomko** [comment]
This is minor, but can we update the error message text? Can we remove the word "currently" from the text so it reads "The visualization cannot be made because there is no plottable data for selected variable(s) in the current subset."

<img width="1116" alt="Screen Shot 2022-04-11 at 3 07 12 PM" src="https://user-images.githubusercontent.com/54597319/162823171-7fb68ea8-e967-4d2e-a6b1-a566cb4b0cc0.png">

**Comment by moontrip** [comment]
@SheenaTomko I am working on another scatter plot bug ticket so I can change the sentence with your suggestion sometime this week 😄.

**Comment by SheenaTomko** [comment]
DK's PR fixed this text. Closing this and marking as complete
