### ISSUE TITLE
Update UI for line plot viz tool, including addition of geometric mean option

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#1038]
Came up in the Uganda meetings. Geometric mean can be more useful for looking at variables with exponential growth, like parasite densities. We'd like to add geometric mean as an option for aggregating and plotting continuous data on the Y-axis of a line plot

**Comment by d-callan** [comment]
i have a number of questions here about how wed like to actually find this value w possible implications to the ux around doing so.  For ex, the presence of 0, negative or % values will be trouble for various reasons. So i guess my questions are:

1. Do we know if we definitely do or dont have percent values for variables? If we do, are there too many to annotate and potentially constrain against? Should we risk allowing users to calculate geometric means on percents directly?
2. Should we consider a client-side limitation that geometric mean only become available if the variable metadata range min is > 0. (I imagine some day w derived variables this would mean users could transform anything they liked to an appropriate range, but they wouldnt be able to easily 'transform' the geometric means in vizs back to something understandable directly relative to the original data range. i personally think thats probably ok particularly given this seems otherwise the safest route.)
3. Should we try to come up w a reasonable rule-of-thumb for how to find the geometric mean in cases where the min value is <= 0 and hope statisticians dont get too mad at us for potentially doing things differently to what theyd have done or for not handling some edge case well or something?

**Comment by d-callan** [comment]
1. good to know there are relatively few percents.. is that 55 the number of IRIs that are known to represent percents? or the number of times we see one of those IRIs used in a study? If we constrain to only variables w >0 or >=0 values, do we know what proportion of those terms represent percents? (it seems still kind of bad to me if a user toggles to only compatible variables for some study and a large number of those were percents, but its probably unlikely?)
2. i guess theres a question whether it should limit against 0 arising vs just negative values? I can probably imagine scenarios where treating 0 as empty would be bad as well.. and it seems a thing only the user would know whether they wanted to do based on context. This was my original concern w point 3 really. if we make that decision, what are the chances itd be confusing or frustrating to people in the general case? id be personally inclined i think to answering the questions here around negative and 0 values consistently at least, even if we cant identify percents to handle those consistently as well.
3. If we impose a limitation i think we should never see an error? user just wont be able to select geometric mean for variables w incompatible values. (though admittedly that limitation would be based on the entire study rather than the subset, so you could never filter away values until you had only compatible ones remaining)

**Comment by d-callan** [comment]
depends on veupathdb/plot.data#162

**Comment by danicahelb** [comment]
Discussed in 5/2/2022 EDA UX meeting

The geometric mean applies only to positive numbers. The geometric mean is often used for a set of numbers whose values are meant to be multiplied together or are exponential in nature, such as a set of growth figures: values of the human population or interest rates of a financial investment over time.

**Variables where the metadata range minimum is negative:**
- Most variables do not have negative values
- The only place this will consistently be an issue is with z-score variables. 
- We will inform the user that the negative values are being stripped out. The geometric mean radio button will be labeled: `Geometric mean (will exclude values <0)`

**Variables that include values equal to zero:**
- The geometric mean of a data set with at least one zero is always zero. As a result, the geometric mean does not capture any information about the non-zero values.
- Based on context, sometimes users will want to treat zeros as nulls and sometimes they will want to treat zeros as 0. Example: geometric mean of Plasmodium density, where values of 0 indicate that no parasites were found
- We will offer users the ability to choose to include data values of zero, or to strip them out (ie, set them to null)

**Variables that are percents:**
- It is misleading to calculate geometric means on percentages
- Across all studies, we currently have 55 unique IRIs that are percents. 
- Since there are so few percentage terms, we will risk allowing users to calculate geometric means on percents directly
- All terms that represent percentages have “(%)” in the label, for example: “Calories from fat (%)”. We can leverage labeling protocols to identify percentage terms without having to manually annotate them
- A warning will be displayed when a user wants to display the geometric means on percentage terms
- When the unit conversion system is in place, we can consider allowing users to convert percents to proportions
- It would be bad for a user to toggle only compatible variables for some study and a large number of those were percents, but this is not currently an issue

@danicahelb will mock up adding geometric mean to line plot, to be discussed in a future EDA UX meeting

**Comment by danicahelb** [comment]
Final mockups:

<img width="876" alt="image" src="https://user-images.githubusercontent.com/25450900/172225649-fcf7ac58-99eb-4a79-8350-e0a2d1e4d05e.png">

<img width="874" alt="image" src="https://user-images.githubusercontent.com/25450900/172225838-81dd0c5e-1702-4b8d-8c60-e4a5a7239ded.png">

<img width="877" alt="image" src="https://user-images.githubusercontent.com/25450900/172225944-b51cbcb4-3717-4ada-8dcf-05fd3ce99f99.png">

<img width="874" alt="image" src="https://user-images.githubusercontent.com/25450900/172226092-1821a81a-d52c-4c38-8a8e-d6136744a574.png">

**Comment by danicahelb** [comment]
The goal of this ticket is to separate out "Y-axis aggregation" UI for continuous vs categorical Y-axis variables:
- [ ] when no y-axis variable has been chosen, indicate `First select a Y-axis variable` (in gray text)
- [ ] when a continuous Y-axis variable has been chosen, update the header to `Y-axis aggregation (continuous Y)`
- [ ] when a continuous Y-axis variable has been chosen, implement dropdown to allow user to choose between (i) arithmetic mean, (ii) median, or (iii) geometric mean. Arithmetic mean should be selected by default
- [ ] when a categorical Y-axis variable has been chosen, update the header to `Y-axis aggregation (categorical Y)`
- [ ] when a categorical Y-axis variable has been chosen, implement value selector dropdowns so the user can configure their proportion. No default selections should be made for the numerator; denominator should have ALL possible values selected by default

Improved UI to indicate proportion needs to be configured (by red text & note on plot area) will be handled in: https://github.com/VEuPathDB/web-eda/issues/1080

**Comment by SheenaTomko** [comment]
Works as expected and looks good
