### ISSUE TITLE
Line plot is empty if overlay variable only has data for one value

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#1069]
If I add a filter to only include data where lost earnings due to care = yes, then the plot is empty. I would expect the plot to still have the same blue line

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/25450900/163481317-83585ae0-2c2f-4841-bbb1-5898a1794211.png">

_Originally posted by @danicahelb in VEuPathDB/plot.data#157

**Comment by asizemore** [comment]
Looks to be a front end issue. The lineplot response looks like it contains everything

<img width="1772" alt="Screen Shot 2022-04-15 at 9 26 42 AM" src="https://user-images.githubusercontent.com/11710234/163576534-ace6de51-2e95-4d2f-8739-05909e9b80be.png">

**Comment by aaronwlsong** [comment]
It seems the issue still exist in certain studies. like GEMS1 Case control.

No matter add or not add overlay variable, the plot is always empty. See pic 1 (without overlay var) and pic 2 (with overlay var)
pic1
<img width="1878" alt="Screen Shot 2022-04-15 at 4 49 54 PM" src="https://user-images.githubusercontent.com/61077845/163630836-e44f0350-1ad9-4648-9ff1-1f01ed7c6c7b.png">

pic 2
<img width="1834" alt="Screen Shot 2022-04-15 at 4 45 56 PM" src="https://user-images.githubusercontent.com/61077845/163630858-11c012d7-7258-4c29-bc8f-dfef5ef15205.png">

Same thing happens in another study LLINEUP RCT. (when x=age, y=study timepoint and overlay var only filtered as "PBO LLIN")

Pic 3.
<img width="2094" alt="Screen Shot 2022-04-15 at 4 57 01 PM" src="https://user-images.githubusercontent.com/61077845/163631493-38e5261e-0898-43a0-a207-fcfdc959ef3d.png">

But test with the same conditions (same x and y vars and filtered overlay var only has "yes") in another study (ELICIT RCT), it looks good. 
<img width="1963" alt="Screen Shot 2022-04-15 at 4 48 54 PM" src="https://user-images.githubusercontent.com/61077845/163630894-6b5be130-03e6-4fb7-a4f9-acdffe2df798.png">

**Comment by danicahelb** [comment]
@aaronwlsong when the y-axis data is categorical you need to set up your proportion for the plot to populate. I made the same mistake... the line plot in proportion mode needs more inputs than the rest of our plots. I made this ticket to address this question https://github.com/VEuPathDB/EdaNewIssues/issues/245

**Comment by danicahelb** [comment]
Once the proportion is configured, I get the plot I expect 
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/25450900/163635206-9e76db05-99cb-4552-a3b0-b0a8d355676e.png">

**Comment by danicahelb** [comment]
@dmfalke made the following note in the pull request: 

I'm not completely satisfied with this solution, as it seems to rely on Plotly.js's behavior to treat such elements as "empty". I think a better solution would be to remove the entry from the data array, but this requires some reworking of how [legendItems is constructed](https://github.com/VEuPathDB/web-eda/blob/9cbf9b2656206e32fbfe64557732e9fab45d599d/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx#L633-L676). I will make an issue (https://github.com/VEuPathDB/web-eda/issues/1071) for this as a follow-up, since I don't want to mess with the current logic right now
