### ISSUE TITLE
Remove extra labeled x-axis markers when binning by year 

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1081]
when i turn on binning by date and choose year, I am getting labeled x-axis markers every 6 months. please only include 1 labeled x-axis marker per year (ie, january XXXX) and remove the labels for the 6-month markers

<img width="651" alt="image" src="https://user-images.githubusercontent.com/25450900/163242169-182b247a-3f38-4156-a11d-bf5ab5cdf1aa.png">

**Comment by bobular** [comment]
Just a comment that the more we fiddle with Plotly's default axis behaviour, the more problems we may create down the line. Remember we had y axis tick labels: 1, 1, 1, 1 (or something like that) in log scale mode?  That was because we were trying to be clever and didn't use the default tick label format.

That's not to say we can't do something here, I'm just saying it may have a cost.

**Comment by bobular** [comment]
> may be related to #872

I think the solution I'm thinking of could fix this too.

**Comment by aaronwlsong** [comment]
Use LLINEUP rct to test, the setting is in attached screenshot. Looks like now all month are removed and only year is kept. 

![Image](https://user-images.githubusercontent.com/61077845/220699518-317332fd-58ff-4de6-8f83-2a08f77adab1.png)
