### ISSUE TITLE
Update UI for viz tools

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1322]
Related to https://github.com/VEuPathDB/web-eda/issues/1177
Discussed at 8/15/2022 EDA UX mtg. Decisions:

- [x] Remove (optional) from Stratification variables (optional) label
- [x] Change the Required input mouseover text to Required parameter
- [x] Add: Please select all required* parameters. to all viz tools when all required parameters have not been selected. _e.g., opening up a new viz tool would always have this text in the plot window since x-axis and y-axis variable had not yet been selected_
- [x] Required parameters will be marked with an asterisks (ex: X-axis*) and will be in red text until a selection has been made. After a selection is made, the text should turn black

<img width="524" alt="image" src="https://user-images.githubusercontent.com/25450900/184713649-4732be00-c1cd-4448-87a8-617eedfe48fd.png">

**Comment by jernestmyers** [comment]
The latest changes [to this PR that addresses all inputs except for `Y-axis aggregation`](https://github.com/VEuPathDB/web-eda/pull/1245) are shown in the screenshots below. Of note:
1. I've chosen to push the required inputs prompt to the right in order to A) avoid any issues with very long y-axis labels and B) avoid the zoom in/out map controls.
2. The overlay is difficult to see without a background, but the background then makes it look like a banner. It's especially difficult to see in the satellite layer, as shown. I'm unsure how best to approach this particular visualization and welcome any suggestions.

![image](https://user-images.githubusercontent.com/69446567/185479987-fc2d2708-b104-45c5-b0c6-761ba2db8814.png)

![image](https://user-images.githubusercontent.com/69446567/185480008-d65ce7df-19e8-4f81-8467-a32823917a93.png)

![image](https://user-images.githubusercontent.com/69446567/185480072-b01d363b-8dce-4105-a3d0-08879f5be1c4.png)

**Comment by danicahelb** [comment]
Thanks @jernestmyers. I think we should go with the version with the white background for b59. We can discuss further styling changes at a later date.

**Comment by SheenaTomko** [comment]
Changes look good. The red is very in your face.
