### ISSUE TITLE
Reserve space between plot area & controls for content message

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1502]
Plot controls are not in the same position after the content message appears.

The content message currently pushes all of the plot controls down when it appears. Please instead reserve space for banner under Scatterplot (and also under all other viz tools to accommodate future content messages)

We do not want there to be an oversized white space gap under the plot when there is no content message, so please make the content message less tall and remove any gaps between the content message and the plot controls

**Comment by danicahelb** [comment]
in 10/21/2022 EDA UX meeting we had decided that: 

> There can be more than 1 plot control banners
> if 2+, the banners will be stacked. 

I suggest we start by leaving space for 2 banners & see how it looks

**Comment by moontrip** [comment]
@danicahelb I am afraid that I am confused about the behavior of the banner, so please correct me if I am wrong. Do you want to leave a banner permanently after a banner is called? Currently, the banner behavior is like this: a) make a banner disappear if an addition change of a plot control by user is irrelevant to banner. For an example with Lineplot Viz, a banner is shown if user toggles on the log scale control while the error bar toggle is on. Under this condition, if user toggles off the log scale control, the banner disappears; b) make a banner be replaced with another banner because additional user action to trigger a new banner is unrelated to the previous action. So we currently show single banner depending the state of user's actions and those actions are irrelevant each other.

For reference, speaking of a possible number of banners, there are five banners for Scatter plot Viz and four banners for Lineplot Viz. The former cases are: 1) no smoothed mean; 2) X log scale and Smoothed mean; 3) Y log scale and Smoothed mean; 4) X log scale and Best fit; 3) Y log scale and Best fit. The latter cases are: 1-2) while X log scale on,  toggle on Bin, and vice versa; 3-4) While Y log scale is one, toggle on Error bar, and vice versa. Assuming that we will always keep banners, e.g., a user took actions of 1) and 2) with Scatter plot, which will have two banners, then what should we do if user will take another action of 3)? Removing the banner 1), moving up/down the banner 2), and showing a banner 3) to the empty place? If this is what you want, it is not that simple task to implement those behaviors because certainly current banner does not have that feature: it is designed for a single banner at each case. Honestly, I cannot estimate exactly how long it would take to make them happen.

**Comment by danicahelb** [comment]
Hey @moontrip 
(banner is wrong verbiage, we should use context message. i corrected my post above) 

we do not want to leave a context message permanently after it is called. it should only be visible when the user selections are incompatible. the current behavior is what we want.

**Scatter currently has only 2 content messages, and you cannot get message 2 at the same time as message 1:**

1. `Log scale is not available for plot modes with fitted lines. Why?`
- X log scale and Smoothed mean
- Y log scale and Smoothed mean
- X log scale and Best fit
- Y log scale and Best fit

2. `Smoothed mean(s) were not calculated for one or more data series. Why?`
- no smoothed mean for 1+ data series

**Line plot should has only 2 content messages, and you CAN get both at the same time:**

1. `Log scale and binning are not available concurrently. Why?`
- while X log scale on, toggle on Bin
- while Bin on, toggle on X log scale one

2. `Y-axis log scale and error bars are not available concurrently. Why?`
- While Y log scale is one, toggle on Error bar
- While Error bar is one, toggle on log scale

(note, i've updated the verbiage for the line plots for the transition from snack bars to content messages)

3-4) While Y log scale is one, toggle on Error bar, and vice versa.

**Comment by moontrip** [comment]
@danicahelb Thank you for summarizing my questions much more clearly. Now it is much simpler to do than what I initially thought. May I ask one question? Since we have two possible messages at each Viz at the same time, I think that you don't mind to fix the location of each banner. For example, we have two rows for two banners. So, Message 1 is always shown at the first row, and Message 2 is at the second row. I think that a flexible position is quite tricky to implement, so I prefer to having a fixed position per message.

**Comment by danicahelb** [comment]
thats fine, thanks @moontrip!

**Comment by danicahelb** [comment]
looks great, thanks @moontrip!

**Comment by moontrip** [comment]
My pleasure 😃
