### ISSUE TITLE
add citation information directly to download tab

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1510]
On the downloads tab, add the citation for data accessed via ClinEpi as it should appear in any publication citing that data.

**- [ ] For each version of the full dataset, add another row under `"Change log" `**
- verbiage: `Citation: Dorsey G, Kamya M, Greenhouse B, et al. Study: PRISM ICEMR Cohort. ClinEpiDB. 03 March 2022, 21 (https://clinepidb.org/ce/app/workspace/analyses/DS_0ad509829e/new/download)`
- use the same font & styling as used for "Date" and "Change log"
- info in the citation should be specific to each release version (ie, need to change the date and release number)

**- [ ] For the subset downloads, add another row under `Configure and download one or more tabular files of the filtered dataset`**
- the info in this citation should be exactly the same as the citation for the latest release
- use same font & styling as used for the citations for each version of the data

**- [ ] Also add verbiage to the top of the download page: `Please cite that you accessed data via ClinEpiDB`**
- this information can be added to the italicized text at the top of the page (for example, `Data downloads for this study are public. You can download the data without logging in. Please cite that you accessed data via ClinEpiDB.`)

**Comment by dmfalke** [comment]
Assuming the constituent pieces of the citation are available in the dataset record, this should be low cost.

**Comment by danicahelb** [comment]
Discussed in 2/27/2023 EDA UX meeting.
We want to add the full citation text and also a button to download the citation in the header for each download version. 

Citation information for each study can be pulled from ClinEpiDB.xml and eupathBuildDates.yaml files.

1. authors: `primaryContactID` and `contactID` in ClinEpiDB.xml
2. study name: `displayName` in ClinEpiDB.xml
3. date of release: `relDate` in eupathBuildDates.yaml
4. release number: `history buildNumber` in ClinEpiDB.xml 
5. study page URL: this is the URL for the download tab for the study

It would be great to offer different versions of the citation download (@asizemore's idea), see `Cite` button here: https://academic.oup.com/comnet/article/2/3/203/2841130?login=false

<img width="698" alt="image" src="https://user-images.githubusercontent.com/25450900/221660881-617c115b-8cc0-43a4-a89e-c9ff9746abae.png">

**Comment by nkittur-uga** [comment]
The ClinEpi outreach team (Danica, Sheena, Nupur) reviewed Figma mock-ups and have the following feedback/suggestions: 

1. **Citation info for past releases**: We reviewed your two options, and vote for a third option (modification of your option 2)- Display a non-copyable citation string in the button's text and don't have any copyable string when data is expanded. This will result in having the citation visible even when data is not expanded, and there will be no duplication of the string. We understand that it won't be copyable but we can live with that. 

2. Tooltip and cursors: These are not required at all. 

3. We would like the citation string to have a few changes so it reads like this: 

Dataset citation: Dorsey G, Kamya M, Greenhouse B, et al. Dataset: PRISM ICEMR Cohort. ClinEpiDB. 03 March 2022, Release 21 (https://clinepidb.org/ce/app/workspace/analyses/DS_0ad509829e/new)

- Instead of "Citation", make it "Dataset citation"
- Instead of "Study", change to "Dataset"
- Instead of "21", change to "Release 21"
- Instead of link going to download tab, make the link go to the main analysis page

(List continues in next comment)

**Comment by nkittur-uga** [comment]
4. Currently, the citation string is repeated under "My Subset" and "Full Dataset". Instead remove it from these two places, and move it to the top of the page under Data Accessibility. So it will look something like this--

Data Accessibility: Protected
You have been granted access to download the data. Please cite that you accessed data via ClinEpiDB.
Dataset citation: Dorsey G, Kamya M, Greenhouse B, et al. Dataset: PRISM ICEMR Cohort. ClinEpiDB. 03 March 2022, Release 21 (https://clinepidb.org/ce/app/workspace/analyses/DS_0ad509829e/new)

**Comment by jernestmyers** [comment]
Thanks for the feedback!

I have some concerns about the formatting request for the study author(s). I don't feel like we could reliably adhere to the `LastName FirstInitial` format on the client. While it may be a moot point for now since we won't list out _**every**_ contact, there are names that would make things tricky to format. My initial thought was to split the names at the spaces, but this is problematic for last names  that include spaces (see Amazonia Brazil) or Jrs (see 2nd contact in WASH Kenya).

I notice that the screenshot of the "upgrade option" shown above in this ticket simply displays the full name of the author(s). Could we do the same, since that is currently the format of the data given to us from the backend (and the screenshot suggests it's an acceptable practice)? Otherwise, I feel the model needs to add a new attribute for the author's formatted name.

Tangential to this, are we always wanting to list no more than 3 authors?

**Comment by nkittur-uga** [comment]
@jernestmyers Yes, I think it is fine to display the full name of the author(s).

Yes, we should list no more than 3 authors followed by et al. Some of the author lists are very long and would not be reasonable.

**Comment by jernestmyers** [comment]
Here's a screenshot with full names displayed:
![image](https://user-images.githubusercontent.com/69446567/228653927-4564de5a-4857-4e1c-82fd-2cd147b43410.png)

Also worth noting that I've currently opted for `Dataset Citation` versus `Dataset citation` since the download tab seems to enforce the capitalization. In fact, the "subtext" in the expandable release buttons enforces this style of capitalization, as seen in Change Log.

**Comment by danicahelb** [comment]
@jernestmyers what is the plan for the button to copy citations? if we are going to offer the different formats we really should include all of the authors there (as different journals have different requirements for the citations). perhaps this should be moved to a separate ticket for a later release.

**Comment by jernestmyers** [comment]
> @jernestmyers what is the plan for the button to copy citations? if we are going to offer the different formats we really should include all of the authors there (as different journals have different requirements for the citations). perhaps this should be moved to a separate ticket for a later release.

The current implementation only allows a user to copy the citation to the clipboard. The user can click either the citation string or the "Copy" icon in order to do so.

The upgrade option shown above would entail some backend work, which is probably better suited as a follow up ticket and/or for next release.

**Comment by danicahelb** [comment]
thanks. ticket to upgrade copy citation button is here: https://github.com/VEuPathDB/EdaNewIssues/issues/610

**Comment by danicahelb** [comment]
It's looking pretty good! a couple of things: 

please don't italicize the citation. 

To separate the citation from the text above, please add a small line break and possibly also use the bold (semi-bold?) font used for `Date` and `Change Log` under `Full Dataset`

thanks @jernestmyers!


![Image](https://user-images.githubusercontent.com/25450900/231909192-719ad375-d583-4b3c-bba1-11ef93eb45fc.png)

**Comment by danicahelb** [comment]
also, I'm checking in with @dpbisme and @asizemore to see if they are happy with how the citation looks on mbio. On mbio studies, the only author is the primary contact



![Image](https://user-images.githubusercontent.com/25450900/231910182-65a8d29f-2482-4ed3-80a3-47c98c71fca7.png)

**Comment by asizemore** [comment]
Is that because mbio only has the primary contact filled out in the presenters or some place?

**Comment by jernestmyers** [comment]
> It's looking pretty good! a couple of things:
>
> please don't italicize the citation.
>
> To separate the citation from the text above, please add a small line break and possibly also use the bold (semi-bold?) font used for Date and Change Log under Full Dataset

I'll try a couple ideas and post screenshots for review. @asizemore [didn't like the idea of using bold](https://github.com/VEuPathDB/web-monorepo/pull/14#issuecomment-1497193852) on the citation. When I looked at it with italics vs no style, the italics felt better at the time.

**Comment by asizemore** [comment]
Thank you for the screenshots! That was super helpful.

I also vote for 2. The bold makes it jump up in the visual hierarchy at an odd spot. Leaving it unstyled gives me a better chance of actually seeing the "Dataset Citation" heading. In the layout we have, the heading is what we want the user to see, more than the citation itself. Anyone looking for a citation is going to scan the page quickly for the word "cite" or "citation", which they can quickly find in the header. That section is super short so once they find the section they are looking for, they should have no problem finding the content they need.

**Comment by danicahelb** [comment]
Would we want to consider moving the citation after Dataset citation? so the header would look like this:

`**Dataset Citation:** Dorsey G, Kamya M, Greenhouse B, et al. Study: PRISM ICEMR Cohort. ClinEpiDB. 03 March 2022, 21 (https://clinepidb.org/ce/app/workspace/analyses/DS_0ad509829e/new/download)`

**Comment by asizemore** [comment]
Do you mean having the citation in the header as well? I think having that large of a header would impair a user's ability to focus on other parts of the page.

**Comment by nkittur-uga** [comment]
Looks great! 
<img width="1213" alt="Screenshot 2023-04-28 at 10 51 25 AM" src="https://user-images.githubusercontent.com/67710160/235180787-aeac26a2-1edb-49ea-a746-9e6e9c15274d.png">
