### ISSUE TITLE
Update verbiage for all toggles on all viz tools

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1517]
Toggle is not in the same position after turning on… user needs to move mouse to turn it back off

In the 12/2/22 EDA UX meeting, we decided that our POLICY will be that verbiage will NOT change based on the toggle position

Log scale plot controls should say: `Log scale (excludes values ≤ 0)`, regardless of whether the toggle is on or off

Please update the verbiage for the log scale toggles on all viz tools

**Comment by danicahelb** [comment]
Similarly, please change the verbiage for ALL toggles such that the verbiage does not change based on the toggle position



![Image](https://user-images.githubusercontent.com/25450900/207420818-57e1293b-995e-4439-860e-1f980dc42526.png)


Change `Binning on` / `Binning off` to just `Binning`

Change `Error bars on (95% C.I.)` / `Error bars off (95% C.I.)` to just `Error bars (95% C.I.)`

(I don't think there are any more toggles)

**Comment by aaronwlsong** [comment]
Tested the toggle position (toggle is on and off), toggle names (Binning instead of Binning on/off ), and words (Whether it only keeps Error bars (95%C.I. )).

Tested study:  Amazonia ICEMR Brazil Cohort / line plot ;   GEMS1 Case Control / line plot

Looks good now, closing ticket. 



![Image](https://user-images.githubusercontent.com/61077845/210598063-b1743993-9dfc-4922-95b4-ac23d0566a96.png)


![Image](https://user-images.githubusercontent.com/61077845/210598062-6400273d-5b18-4764-ba86-a4ab5396a8bd.png)


![Image](https://user-images.githubusercontent.com/61077845/210598815-7c3a5e17-11ad-4ec6-a3ab-a9d93671fc12.png)
