### ISSUE TITLE
Visualizations: Scatter plot opacity slider defaults

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#1605]
I think we should change the default value for the opacity slider to something between .5 and .7 .. its way easier to see overplotted regions of the plot that way. 

also, i think if the user changes the value of the slider, it should be remembered when changing variables rather than going back to default.

**Comment by moontrip** [comment]
@danicahelb @asizemore @d-callan I have one question about the direction of the slider. As you can remember Ann initiated the idea of reverse slider starting from 1 to 0 (darker to lighter) and Danielle liked the idea, but finally Danica wanted to leave it as is (normal slider). 

The final decision was made while I was absent due to my sickness at the end of Jan. So, I missed it and implemented the feature of reverse slider, which is certainly optional/controllable for both normal and reverse slider: https://github.com/VEuPathDB/web-components/pull/450. My question is that do you envision that we will need such a reverse slider in the future? If true, then we will include the reverse feature to the current slider.

**Comment by moontrip** [comment]
Thanks @asizemore for very detailed information.

**Comment by SheenaTomko** [comment]
Looks good

**Comment by moontrip** [comment]
Thanks @SheenaTomko for your reviews and confirmation 👍
