### ISSUE TITLE
handle "expired" jobs by allowing the user to resubmit

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#1637]
Finally hit an expired job!!! Confirmed with the backend band that the expired jobs are intended to be rerun by the user. Let's allow them to do this!

I'd propose the status indicator is gray again, and the text is "Results have expired. Please regenerate the results." 

<img width="925" alt="Screen Shot 2023-02-22 at 11 00 59 AM" src="https://user-images.githubusercontent.com/11710234/220681866-4a656d4a-cefc-43c4-bab1-68d17de9243c.png">

**Comment by asizemore** [comment]
for qa, please test the example given above! see if we can now regenerate results!

**Comment by asizemore** [comment]
<img width="1287" alt="Screen Shot 2023-02-27 at 5 33 36 AM" src="https://user-images.githubusercontent.com/11710234/221540561-d2a9a318-dd3d-44cd-a11f-48cab89c310b.png">

Found another example for testing!

**Comment by asizemore** [comment]
For testing, requires the compute service >v1.3.2

**Comment by SheenaTomko** [comment]
@aaronwlsong, note that you will need to wait to qa this on qa.microbiomedb.org until Ann says the compute service is ready

**Comment by asizemore** [comment]
So far not looking good... the qa site got the new code but we're seeing this error. I sent it to Ryan and Ellie for their thoughts!

This is DIABIMMUNE, beta div, data=Species, method=bray.

<img width="1478" alt="Screen Shot 2023-02-28 at 4 03 21 PM" src="https://user-images.githubusercontent.com/11710234/221979143-5c17351a-e8ad-47de-b63c-10b89b544fef.png">

**Comment by dmfalke** [comment]
@asizemore is it possible https://github.com/VEuPathDB/web-eda/pull/1655 will address the latest issue?

**Comment by asizemore** [comment]
Unfortunately no, as it's in the backend. But Ellie has already made a PR to fix it so hopefully we'll see it all working shortly!

**Comment by asizemore** [comment]
All updated! Please go ahead with QA of this ticket

**Comment by aaronwlsong** [comment]
I tested both of cases aforementioned. For the color of dot: Yes, now it is grey. For the text, instead of showing "_Results have expired. Please regenerate the results_." it shows as "_Not started_". Does not look like the same meaning for me. I will put it under "Failed QA" category. If the text part is an expected, I (or anyone else) can change the status to "Completed".  



![Image](https://user-images.githubusercontent.com/61077845/223135772-19f5c8d1-6ef2-44eb-a291-f101aa8b4efb.png)
![Image](https://user-images.githubusercontent.com/61077845/223135771-7d542cfc-f4e1-4e62-a50f-343aead13730.png)

**Comment by asizemore** [comment]
That's great! The cache got cleared recently so we actually shouldn't be seeing "expired" for a bit :)

I have previously seen an expired job and when I clicked the button to rerun it worked, so i'll go ahead and move this to Complete. Thanks @aaronwlsong for looking into this!
