### ISSUE TITLE
show var completeness table when plot data is empty

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#227]
just tried to plot `sleeping rooms in dwelling count` against `axillary temperature` in a scatter plot for gems1 case control. the response indicates all values are missing for axillary temperature (not sure yet if thats the data or a back end bug, but thats besides the point currently). i think we should show the completeness of the vars even when there is no plottable data.

**Comment by moontrip** [comment]
With the update by Danielle, now I can test this case however it is not clear to me what the issue is exactly. The table is always shown regardless of data or no data, so perhaps your question is to show values in the table (Data and No Data). But your example, sleeping rooms in dwelling count vs axillary temparature throws 500 server error (backend issue) and no proper response is given to the frontend side (like CompleteCasesTable response). Thus it is not clear whether no data will work properly.

@jtlong3rd who made the nice table can answer this more accurately but my gut feeling is that if the response is properly given to the frontend without 500 error, the table would show values, e.g., Data = 0 (0 %), No Data = 10,000 (100 %). By the way, @jtlong3rd, your nice table seems to stop working after recent backend change. Please see [this draft PR](https://github.com/VEuPathDB/web-eda/pull/246) made by Bob whether it would be helpful for you to identify an issue

**Comment by jtlong3rd** [comment]
> By the way, @jtlong3rd, your nice table seems to stop working after recent backend change. Please see [this draft PR](https://github.com/VEuPathDB/web-eda/pull/246) made by Bob whether it would be helpful for you to identify an issue

I'll take a look! I suspect that this is related to the change in the variable id format.

**Comment by moontrip** [comment]
I think this is closely related to #240 so I will also check this as well.

**Comment by moontrip** [comment]
@d-callan After addressing dataElementDependencyOrder (#240), I could test your case, `sleeping rooms in dwelling count` against `axillary temperature` at scatter plot viz. Yes I could see there are many no data for `axillary temperature`, about 30 %, but plot and table are showed accordingly. Thus, as I presumed, they seem to work just fine if the backend responds with data (without server error). Do you think your issue is addressed ?

![scatter-depend0](https://user-images.githubusercontent.com/12802305/127327466-6b632b0f-b3fe-48c2-9198-7c5024e0e788.png)

**Comment by d-callan** [comment]
For now maybe.. I have some lingering concerns but I can open a new issue if I find a good example of one of them.
