### ISSUE TITLE
Visualizations: use variable metadata (annotations) for axes when plotting continuous variables

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#231]
For example, histograms should use the `range{Min,Max}` or `displayRange{Min,Max}` properties to determine the default x-axis range, rather than the range of the data itself. This make plots more consistent. Users can always zoom if they want to.

**Comment by dmfalke** [comment]
This is still somewhat up for debate. Danielle may provide values based on the subset.

**Comment by d-callan** [comment]
so i think this is what we want to do:
1. get the min and max value actually seen for some cont var for the subset
2. compare the annotated min to the min value in the subset. if the min value in the subset is smaller, use the dataset min. compare the annotated max to the max value in the subset. if the max value in the subset is larger, use the dataset max.
3. this can obviously be overridden by the user zooming
4. pass this info as the viewport to histo so it does binning properly
5. for all cont axes where the user specified a var, use this as the range to display
6. for cont axes where the user doesnt specify a var:
     a. if valueSpec is 'count' and the outputEntityId 'Participant' for ex, the axis range should represent the total count of that entity for the dataset. Its possible this rule will need some improvement once we see it, but it seems a reasonable place to start..
     b. if valueSpec is something like 'proportion' we have to make some common sense decisions and set the range 0-1

**Comment by bobular** [comment]
I'd like some clarification on this please.

Does "dataset min" in 2. mean "annotated min"?

Below are two screenshots from the latest dev version (PR #242) I'm working on.  There is no subsetting active.

![image](https://user-images.githubusercontent.com/308639/126981090-ce07572d-fd7b-43ad-b182-3f14ef669d75.png)
![image](https://user-images.githubusercontent.com/308639/126981150-feef6b04-9f2f-440f-a097-af0bf7bee38e.png)

Do we want to see the big gap from 2003 in the viz histogram too?

Note that there are no immediate (this week) plans for user-zooming in the histogram viz.  This needs to be coordinated with #98

**Comment by bobular** [comment]
And here's the HistogramViz when subsetted on just 2010
![image](https://user-images.githubusercontent.com/308639/126981526-143ffef8-4b16-4987-8cfd-76cc52e9b396.png)

It's probably best to meet to discuss :-)

**Comment by d-callan** [comment]
the goal is to keep the axes as consistent as possible, while preferring the annotated range whenever possible.. 

why is there in the subset histo a gap starting at 2003? is that the annotated range?

also, annotated range is different to the dataset range. when i said annotated range i meant the theoretical/ default display range provided by the clinepi team in the owl file. the dataset range i meant to mean the min and max values seen in the complete (not subsetted) dataset.

**Comment by d-callan** [comment]
but sure we can meet if needed

**Comment by moontrip** [comment]
@dmfalke @d-callan and @bobular After checking the current implementations and thinking about other stuffs, here are my thoughts. It would be great if you can leave your thoughts/opinions/suggestions.

First of all, currently plot vizs that support continuous type are histogram, scatter plot, and line plots. Histogram plot at `Browse and subset` tab, so-called histogram filter, is another plot, if we consider it. 

Starting from scatter and line plot vizs, they have circular markers so we had intentionally added margins at lower and upper bounds not to cut the circular markers around the bounds. Technically we just use plotly's default range: previously we used 5 % addition to set range but it was close to the plotly's default range so we just leaf it as was. Thus, I think that we may not use variable's annotated (or called metadata as well) range (min/max) for scatter/line plots anyway. 

As for histogram viz, it does not specifically use range because the plot controls for axis range are not implemented in Phase 1 (see Bob's comment above): currently only histogram filter has them. That is, we simply relies on Plotly's default range, which is certainly data-based automatic range determined by Plotly. Again since we don't use plot controls. Do we still need to set range for this viz ?

Since it is closely related, I will also say about histogram filter (plot at `Browse and subset` tab) that adopted plot controls for axis range. Current setting is that it firstly checks the presence of displayRangeMin/Max at variable's metadata. If exists, they use as axis range. If not, rangeMin/Max at variable's metadata. Note that for numeric data, the range min was implemented by taking the minimum value between zero and rangeMin. Here are a couple of examples to compare variable's metadata (starting with `variable.`) and backend response (starting with `response.`) for min and max (GEMS1 study data).

- sleeping rooms in dwelling count
  response.histogram.config.viewport = [0, 74]
  response.histogram.config.summary.min/max = [1, 74]
  variable.rangeMin/Max = [1, 74] (no displayRangeMin/Max for this variable)

- height
  response.histogram.config.viewport = [0, 117.4]
  response.histogram.config.summary.min/max = [17.4, 117.4]
  variable.rangeMin/Max = [17.4, 117.4]
  variable.displayRangeMin/Max = [0, 121]

- enrollment date
  response.histogram.config.viewport = ["2007-11-28", "2011-03-14"]
  response.histogram.config.summary.min/max = ["2007-11-28", "2011-03-14"]
  variable.rangeMin/Max = ["2007-11-28", "2011-03-14"]
  variable.displayRangeMin/Max = ["2003-01-01", "2011-06-01"]

As you can see, backend response's min/max are the same to variable's rangeMin/Max in all three cases. The enrollment data case also answers the question raised by Daniel [before](https://github.com/VEuPathDB/web-eda/issues/231#issuecomment-886774978), "why is there in the subset histo a gap starting at 2003? is that the annotated range?" It is because displayRangeMin is set to be "2003-01-01", which is currently top priority under the current implementation at histogram filter. On the contrary, histogram viz simply relies on Plotly's range, thus it starts from about "2007-11-28" which is close to variable's rangeMin/Max or backend response's min/max.

So, my question is what we should do under this observation ?

**Comment by d-callan** [comment]
It sounds to me the subset tab is doing it right, and the viz tab should be updated to follow suit. The idea is that if you have some variable w values that could theoretically fall between -10 and 10, then the axis should always show that range. An ex as to why: If a subset happens to only have values between 2 and 5, it's potentially misleading to change the axis to match the subset. First it's a relatively easy thing to not notice, but second it also makes it difficult to compare plots. If we'd like to add margins in the scatter plot I'm fine w that, so long as we do it consistently.

**Comment by moontrip** [comment]
@d-callan Thank you for your detailed information. If I understand correctly, based on your example, we need to show [-10, 10] range regardless of subset filtering that falls in the range of [2,5] ? If we use displayRangeMin/Max (or rangeMin/Max) from variable's metadata as the axis range, then yes we can keep [-10, 10] (or a bit more for scatter plot viz for having some margins).

**Comment by d-callan** [comment]
think this is possibly impacted by #310

**Comment by bobular** [comment]
Testers: please check carefully with known variables that have displayRangeMin/Max.  I was only able to approve the PR using GEMS1A for testing, which doesn't seem to have any such variables.

**Comment by sweverschulman** [comment]
I was able to verify using the following PROVIDE samples for "CO2" and "Methane" both series of vars have deafultMax and Min and bin. The histogram correctly displays the annotated values.

**Comment by moontrip** [comment]
@sweverschulman Thank you for your tests 👍

**Comment by moontrip** [comment]
The scope of work in this ticket is done and merged. However, in this regard, additional work was raised, simply put, adding X and Y axis ranges for scatter plot viz. The discussion is made at Slack ([here]([url](https://epvb.slack.com/archives/C0132PM1MT5/p1631536034100100)))

So, for clarity, I reopen this ticket.

**Comment by moontrip** [comment]
Hi @sweverschulman, I guess you would review this again so I leave an information for you 😃 In this case, you can only test Scatter plot viz for both independent and dependent axes' ranges, especially for the latter.

**Comment by danicahelb** [comment]
@sweverschulman please test this ticket and let us know if we can close it

**Comment by sweverschulman** [comment]
I was able to verify functionality in the scatterplot in Wash B Kenya using 'Length- or height-for-age z-score, using median stature' and'Head circumference-for-age z-score, using median circumference'. Unfortunately both have the same range.
<img width="984" alt="Screen Shot 2021-10-06 at 3 06 49 PM" src="https://user-images.githubusercontent.com/62298921/136267680-df815440-4a57-4743-9d94-88329ba6fa26.png">

But if you switch vars to one with constraints and one without the axis change accordingly 
<img width="938" alt="Screen Shot 2021-10-06 at 3 10 28 PM" src="https://user-images.githubusercontent.com/62298921/136267766-8bc5fd94-eb2b-4294-a0af-8886b0b48cd8.png">
