### ISSUE TITLE
Subsetting: Update how original variable names appear

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#290]
The "Original variable name" under the label for each variable currently looks like:
Original variable name: ["F4A_FUEL_ELEC","F7_FUEL_ELEC"]

Need to update this to 
1) remove the brackets
2) remove the quotation marks
3) add a space after commas separating multiple variables

Should look like:
Original variable name: F4A_FUEL_ELEC, F7_FUEL_ELEC

**Comment by dmfalke** [comment]
It looks like this is being formatted as a JSON string on the backend somehow. Is there a way for this to be formatted as Sheena suggested instead? It can be done on the frontend, but it adds unnecessary complexity.

**Comment by moontrip** [comment]
This work extended to include the treatment of lengthy variable names for multifilter case. See the comment in the link and follow-up discussions after that.

https://github.com/VEuPathDB/web-eda/issues/380#issuecomment-931733308

**Comment by moontrip** [comment]
@danicahelb @SheenaTomko 
I have tested the lengthy variable names for multifilter case as written in my previous comment above. Since there was no definite solution you wanted, a couple of solutions were tested as follows. Please see the screenshots below and let me know which one is better or other approach would be welcome as well.

(For @dmfalke only: I have also tested the component you did let me know, `OverflowingTextCell` at wdk-client, but it did not work for this case: just showed full list of variable names at single line without having Read more link. Didn't carefully checked the code but from my glance I guess that it is because the area to display variable names does not have specific width property so it did not have ellipsis effect)

Certainly, single variable (i.e., not multifilter variable) is shown as the single line without a link to show/hide, e.g.,
![single variable](https://user-images.githubusercontent.com/12802305/135903417-cf4aa9aa-cc40-4a2e-b327-34f852b36343.png)

# showing three variables at single line and then add show more/less link (the link is text-based one)
- before pressing the link
![multifilter-variable-line1](https://user-images.githubusercontent.com/12802305/135902554-0f1153ab-67a2-4a2d-8072-2396105e1706.png)

- after pressing the link
![multifilter-variable-line1-after](https://user-images.githubusercontent.com/12802305/135902573-519c824c-f4f6-4171-b1f3-5bbfe5dbac2e.png)

# show/hide all style: single line per variable and the link is button style (like `Download` or `+ New analysis` links on top of the page)
- before pressing the link
![multifilter-variable1](https://user-images.githubusercontent.com/12802305/135902663-c63b364f-9d94-43ab-866c-719a342ee141.png)

- after pressing the link
![multifilter-variable1-after](https://user-images.githubusercontent.com/12802305/135902680-f6fe7288-7635-4fae-aa74-f5a864a873af.png)

**Comment by SheenaTomko** [comment]
I like the first option of showing 3 variables by default, then the link to show more. I think with that option, using text wrapping as you show makes more sense than splitting each variable onto its own row.

**Comment by moontrip** [comment]
> I like the first option of showing 3 variables by default, then the link to show more. I think with that option, using text wrapping as you show makes more sense than splitting each variable onto its own row.

Thank you for sharing your thought @SheenaTomko 👍 I think perhaps underscore at Show More/ link is not required so I will remove it when making a PR.

**Comment by moontrip** [comment]
@danicahelb Thank you for your suggestions! I will make sure that I will handle those two for phase 2 😃
