### ISSUE TITLE
General: grey and red colors in browse/subset histogram do not match colors in entity diagram

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#301]
![image](https://user-images.githubusercontent.com/25450900/128941532-35837583-92f4-4c08-9206-3d690693c67b.png)

The grey & red colors in the browse/subset histogram should match the grey & red used in the entity diagram.

Before adjusting, wait for a final decision on what colors we will use in the birds eye view bar summary, as this will impact the red color that we should use for the browse/subset & entity diagram

**Comment by danicahelb** [comment]
can we tone down the colors in the browse/subset histograms & bar charts to match the colors in the entity diagram? seems to me that the same colors should be used across the site. 

I can add this to next Monday's EDA meeting agenda if it warrants discussion

**Comment by asizemore** [comment]
@danicahelb and others, what do you think of the screenshots below using the muted colors for the histogram (top) and table (bottom)?
<img width="1773" alt="Screen Shot 2021-09-02 at 3 34 57 PM" src="https://user-images.githubusercontent.com/11710234/131906414-afed0261-a21c-4e5b-bd0d-a04e3e3fff98.png">
<img width="1770" alt="Screen Shot 2021-09-02 at 3 50 37 PM" src="https://user-images.githubusercontent.com/11710234/131907231-0ad08e34-a97f-427d-b86a-b17b70ec630a.png">


Importantly, the top I could implement in `web-eda` because the histogram colors are defined here and then passed to the histogram component. From what I understand, the colors for those bars in the table are defined in [WDKClient](https://github.com/VEuPathDB/WDKClient/blob/master/Client/src/Views/Question/Params/FilterParamNew/FilterParam.css) (see `.fill.filtered`). So the above table is just a "fake" implementation with chrome devtools changing the colors, but to actually make this change in the table we'd need to update the WDKClient css or pass the info to that component (@bobular  @dmfalke curious about your opinions as well!). I'll look into these options but either way let me know if you like the above change!

**Comment by dmfalke** [comment]
This looks good to me. I think I’d like to update the code in WDKClient to
allow the colors to be passed in as props, rather than being specified in
css. The props can be optional and default to the current colors. Is this
something you’d feel comfortable taking on? I can field any questions you
may have.

**Comment by asizemore** [comment]
Awesome thanks @dmfalke! I'll give it a shot and let you know if I run into any trouble!

**Comment by nkittur-uga** [comment]
QAed in GEMS1A. The new muted pink does appear in the histograms and frequency graphs. However it is not implemented in the multifilters.

**Comment by asizemore** [comment]
Fixes merged. Will be qa-able once deployed.

**Comment by SheenaTomko** [comment]
looks good
