### ISSUE TITLE
Visualizations: user friendly abort message when trying to plot too much data 

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#324]
As discussed in 8/16 EDA meeting:

Don’t implement new variable constraints

If there is too much data, show an error message indicating that the user is trying to plot too much data & that they should subset the data further or try a different plot type 

Data service API will need user friendly abort messaging (Backend currently returns 400 response (or 422 user input error) and the client is displaying this message)

We recognize that the backend will try to make the plot for ~30s before throwing up the error message, this delay is OK

**Comment by bobular** [comment]
I'm happy to look at the front end part of this. Is the back end part done or in progress?

**Comment by d-callan** [comment]
it is not.. and id guess probably requires some discussion on how to best implement, decision-making wrt what cut-offs should be per viz, and id guess some time from @ryanrdoherty..

@danicahelb if we dont mean to have umsp or maled until phase 2, can this possibly wait?

**Comment by d-callan** [comment]
talked w ryan, decided to send the data to R, count rows there and return that number to java to throw the 422 if needed. hes also offered to give this a go, hopefully today.

**Comment by ryanrdoherty** [comment]
I put a mechanism in place which throws 400 if the subset size is over a (optional) limit imposed by the client.  @d-callan is refining it to incorporate missingness of the plotted vars so we don't over-protect.  Those changes are on her "limit-request-sizes" branch and I'm not sure of the status.  @dmfalke, can you add what you think is a reasonable limit to scatterplot requests and start using this?  barplot will also need it but that is on Danielle's branch.

**Comment by d-callan** [comment]
That branch could probably be merged, if needed. There is one unresolved comment from @ryanrdoherty that I was hoping to address first, but I'm not sure I'll have the time currently. It could equally be addressed at a later date.

The only place besides scatter that I think may currently need this would be for boxplot requests that ask for 'all' points.

**Comment by bobular** [comment]
Impediment - bob needs clarification

**Comment by bobular** [comment]
Hi all pushed a [PR](https://github.com/VEuPathDB/web-eda/pull/494) (with a screenshot) to start addressing this.

The boxplot viz doesn't currently have any user-controls to request all points, and thus show a beeswarm-like plot alongside the box/whiskers. So this isn't currently an issue.  @danicahelb do we want such functionality for Phase 1?

**Comment by bobular** [comment]
I played around with some limits and went for 100,000 as a preliminary choice.

You may find it hard to find a study with more points, so here is a screenshot of the warning message shown when the limit is breached:
![image](https://user-images.githubusercontent.com/308639/135603838-7e39d489-0bc7-4d7b-9156-411ea1c9af75.png)

Regarding the limit/threshold, I found that the following viz in **SCORE Mozambique S. haematobium Cluster Randomized Trial** took around 8 seconds and that's possibly the longest we want people to wait?  That's why I chose 100k limit.  Note that my connection is transatlantic, and I am using my dev server (though I just checked on QA and it takes the roughly same time there).

![image](https://user-images.githubusercontent.com/308639/135604226-6007f90c-ffaa-4816-8040-88c7f8a80e0e.png)

**Comment by bobular** [comment]
Our consideration shouldn't just be time-based I guess.  Plotting more than X points in a certain amount of screen area is pointless too (pun intended?)
