### ISSUE TITLE
Subsetting: update distributions for variables within multifilters

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#358]
As discussed in 8/20 EDA WG:

Update the distributions for variables within the multifilter, for both ANY and ALL

Note that current functionality on live site (any vs all) is NOT correct: 

- If ANY is selected: distributions do NOT update
- If ALL is selected: distributions update to show subset vs entire dataset

Both ANY and ALL should update for EDA

![image](https://user-images.githubusercontent.com/25450900/131589761-aeda7c1e-e909-45bc-8c69-8aeded4bfa85.png)

![image](https://user-images.githubusercontent.com/25450900/131589791-f27c7621-9a24-49eb-ba1b-08e6d5c37de6.png)

![image](https://user-images.githubusercontent.com/25450900/131589816-cde0e4b8-5f75-4346-8bd5-29cd7066feb6.png)

![image](https://user-images.githubusercontent.com/25450900/131589835-4fa0172f-ddea-4a04-bc19-b627be8fb12c.png)

**Comment by danicahelb** [comment]
I'm ok with implementing the functionality of the live site for EDA Phase 1 (so supporting distribution updates for **ALL** but not for **ANY**

I will make a phase 2 ticket for **ANY**

**Comment by bobular** [comment]
If any work needs doing for Phase 1 - I think this needs making clearer.  I'm confused by this whole ticket.

Why update the red/grey bars at all?

If users need to be able to explore which are the common combinations, is what we need here (or as a viz) actually an UpSet plot?

**Comment by bobular** [comment]
Notes from discussion with Danica:

1. Live site behaviour means no updates when "ANY" option is used.  
    - Some feedback for users would be good (note: absent from live site)
    - Danica suggests graying out the entire Distribution column and maybe adding some text in the heading
2. Try to remove update button, and have the counts refresh automatically (in ALL mode), but with throttling/debouncing or other measures to prevent excessive requests going to back end.

**Comment by bobular** [comment]
Hi @danicahelb - I hope you are feeling better.

I have addressed 2. above - the distribution bars update automatically in "all" mode. The button is removed, except for >15 sub-variables.  Even with the button, the update is automatic, but you can make it happen faster by clicking the button.

"Debouncing" is implemented to avoid multiple clicks causing a backlog of requests sent to the server. In Phase 1 we can't cancel requests that have been made, but we will start discussions about that ASAP for Phase 2.  The debouncing delay time increases linearly with number of variables (after minimum of 2 seconds) to avoid a backlog (because we can't cancel yet).  Hence the button for large multifilters.

Regarding communication to the user what the distribution bars represent in the 'any' and 'all' modes.  There is nothing on the live site about this.  Greying out the Distribution column in 'any' mode might not be a good idea. The pink/grey bars are still representing the other non-multi filters, after all.

If this is all going to change in Phase 2 (all filters applied all the time; perhaps adding an upset plot option in multifilter subsetting) then I feel that any non-trivial development in this area would be a poor use of developer time.

Maybe we should roll out the PR as is, and open to discussion?

**Comment by bobular** [comment]
Decided to roll out the new update-behaviour without any major UI/UX changes.  See the PR.

So, for QA testers - please check that multifilters update OK (in "all" mode).  GEMS1A has a range of multifilters, including a huge 59-variable "bacteria in stool" multifilter.  The button re-appears for this one, but it will update the distribution bars without any user-intervention.

**Comment by danicahelb** [comment]
Hi @bobular one thing i noticed is that -- when i add a filter under the multifilter -- the "loading" icon (circle) does not appear right away so there is no immediate indication that the distribution bars will update. Do you think it is possible to have the loading icon come up sooner after a filter has been applied?

Is it confusing to have the "update" button available on multifilters with >15 variables but not on other multifilters? perhaps it would be better to just have the button on every multifilter?

I like that the update button is labeled "update distributions now", it makes its utility very clear.

**Comment by danicahelb** [comment]
With regards to your other comments, I made phase 2 tickets, we can discuss these issues after phase 1 release:
https://github.com/VEuPathDB/EdaClinepiPhase2NewIssues/issues/21
https://github.com/VEuPathDB/EdaClinepiPhase2NewIssues/issues/3
