### ISSUE TITLE
Subset tab: Reduce precision on the mouseovers on histograms

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#362]
Example: Plasmodium asexual stages, by microscopy result in PRISM2 Border Cohort. The default bin width is 35919.2, and so if you mouseover, some bins (like the 3rd one in this case) have a lot of digits after the decimal point. The mean in the stats above is being truncated to 4 decimal places, so recommend doing the same here.
![Screen Shot 2021-08-30 at 2 24 30 PM](https://user-images.githubusercontent.com/54597319/131393747-c5722946-f6d9-4041-ad01-fdf599e3a213.png)

**Comment by SheenaTomko** [comment]
For reference, the live site truncates to 2 decimal places, and this may be even better

**Comment by SheenaTomko** [comment]
Discussed with Ryan, Danielle, and Dave on 9.7.21 and decided that the bin ranges on the histogram should have the same precision as the bin width the user specifies.

**Comment by aaronwlsong** [comment]
It seems ok now. closing ticket. 
______________________________
Replicated and tested the issue with the same variable in both PRISM2 Border Cohort and other study. 

Instead of truncating decimal, the display format has been changed into scientific (exponential) notation.
![IMG_5430](https://user-images.githubusercontent.com/61077845/134686323-2effd3d7-a1dd-45af-b41a-43c3d1693f9a.JPG)
