### ISSUE TITLE
Visualizations: Long error displayed when selecting an overlay in histogram

### ISSUE THREAD

**Issue by SAK22** [VEuPathDB/web-eda#369]
I accidentally picked the wrong overlay in a histogram in GEMS1 (screenshot attached). The error took up the whole page. Maybe if the error should be displayed it could be short?
<img width="1041" alt="Screenshot 2021-08-24 at 07 35 56" src="https://user-images.githubusercontent.com/22981342/130569611-821042f1-2952-45a0-9896-ca14560b0584.png">

**Comment by danicahelb** [comment]
Now I am no longer able to select "Traditional healer, medical expenses amount"
The mouseover indicates I need to select a number or a date, but this variable is a number

![image](https://user-images.githubusercontent.com/25450900/134994134-5d80676c-498c-4beb-9ba1-c7eafb22bbdc.png)

**Comment by danicahelb** [comment]
I can now select "Traditional healer, medical expenses amount" for my x-axis.
I cannot select "Bought remedy or medicine, transport expenses amount" for my overlay. This is because this variable has 9 unique values (only variables with 8 or fewer unique variables can be selected for the overlay)

![image](https://user-images.githubusercontent.com/25450900/135959255-e3c02663-8259-4643-92a3-2b49461c85c4.png)

Since this is the behavior we want, I'm closing this ticket
