### ISSUE TITLE
General: create new icons

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#415]
Discussed in 9/10/2021 UX meeting. Ann (thank you!!!) will create new icons for:

1. “My analyses” icon → table icon with user icon superimposed
![image](https://user-images.githubusercontent.com/25450900/132915854-12f42769-7897-4777-a9ac-433bca0cc4c3.png)

2. “Study summaries table” icon → currently using multifilter icon (see “Table view” on study cards)
![image](https://user-images.githubusercontent.com/25450900/132915907-80c62f45-6800-47ac-a5b4-6131f30e4e2f.png)

3. “Explore” icon → Bar graph with 3 bars and magnifying glass (Ann is pretty much done with this one already)
![image](https://user-images.githubusercontent.com/25450900/132915964-267eeba7-d266-4e4a-851f-32d8b80e4e1e.png)

**Comment by asizemore** [comment]
Two of the above are likely going to be a derivative of a table-like icon. In order to make sure each becomes appropriately separated from the others, I'm collecting everywhere we use a table-like icon. So far I've only found the one below in the subsetting tab which allows a user to download the current subset. @danicahelb are there any others i'm missing or future table-like icons that you expect we'll need?  

<img width="255" alt="Screen Shot 2021-09-13 at 12 24 43 PM" src="https://user-images.githubusercontent.com/11710234/133121220-9d94ef97-05d4-4f44-a02b-8d34ab477ffb.png">

**Comment by asizemore** [comment]
See screenshots (not in the right places, just an easy spot to implement as a test :) )
<img width="288" alt="Screen Shot 2021-09-17 at 4 35 23 PM" src="https://user-images.githubusercontent.com/11710234/133851869-d8ad14d8-5f2a-449c-98ed-88244470eda8.png">
<img width="266" alt="Screen Shot 2021-09-17 at 4 35 27 PM" src="https://user-images.githubusercontent.com/11710234/133851871-ed5d999a-0a74-4066-b60f-a16adc286f90.png">
<img width="174" alt="Screen Shot 2021-09-17 at 4 35 31 PM" src="https://user-images.githubusercontent.com/11710234/133851872-010ade29-60fa-48fd-bed6-6181b26b853d.png">

**Comment by danicahelb** [comment]
Discussed in the 9/17 UX meeting:

**Problem:** should we use a standard icon to represent links to all of the different tables & add labels to differentiate where the links take us? Or should we use table icons that are styled differently?

**Decisions:** 

1. We want semantic uniformity when overlaying icons; the overlaid icon should always be an action (ie, download, explore, …)

2. We will use the general table icon for:
- All studies and Table view (labeled: “Study summaries”)
- My analyses table (labeled: “My analyses”)
- Public search strategies table (labeled: “Public analyses”)
![image](https://user-images.githubusercontent.com/25450900/133871486-5590019a-d424-409f-89a5-73cfe56f7169.png)

3. We will use the table overlaid with the download icon for:
- Visualization data download (label TBD)
- Subsetting results table download (labeled: “View and download”)
![image](https://user-images.githubusercontent.com/25450900/133871492-9b51506d-55b2-409c-88cd-9def783ced86.png)

**Comment by danicahelb** [comment]
Ann, via slack:

In case you need to modify the new icons next week while I'm gone, I've made a folder called [Icons](https://drive.google.com/drive/u/1/folders/1n1GIqxFSg5ezRi-_qFrQsO2KYgwsrsYj) in the eda google drive that contains all of the icons we've made. My main concern is sizing -- there are some tricks it seems to sizing the svg relative to the artboard in order for the icon to line up appropriately with the text. In my few tests (see https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/67), things look okay, but we'll see what happens when they are implemented in the correct locations.

**Comment by bobular** [comment]
There's a technical issue remaining about local dev site vs production/qa sites - another ticket addresses this.
@dmfalke  will add a link.

**Comment by dmfalke** [comment]
https://github.com/VEuPathDB/web-eda/issues/484

**Comment by asizemore** [comment]
Because of the complications Dave mentioned and the delay in being able to use these icons elsewhere (waiting for the My Analysis button), I thought it would be easier to make a separate issue for actually implementing the new icons (#487). Also I'm hoping the separateion makes the progress and dependencies a little more clear :)
