### ISSUE TITLE
Histogram visualization doesn't use variable.binWidthOverride

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#540]
Nor does it use `variable.binWidth` from the study metadata.

As discovered in VEuPathDB/EdaNewIssues#187 

This is a `web-eda` issue.

**Comment by dmfalke** [comment]
My recollection is that the histogram plugin is supposed to determine an appropriate default binWidth for the given subset, using a sophisticated algorithm. @d-callan @bobular can you offer insights?

**Comment by d-callan** [comment]
It does. And so the viz tab has no need for the bin width computed at data load time.. It probably does however need to know if an annotated override exists.

**Comment by dmfalke** [comment]
The client is not specifying the viewport by default. I think the plugin must be doing that, since it does appear to at least be using the data range of the whole dataset. Could you check on that?

**Comment by d-callan** [comment]
for clarity, i dont think the viewport being returned is actually respected by the client any longer if it ever was. there has since been an issue for specifying axes ranges based entirely on metadata. i actually think the fact the view of the subset tab has a different number of bars than the viz tab despite having the same bin width is an ex of what i mean. if the range were also held consistent, it should give the same bins. i think the viz tab is binning over whatever range is available, but should probably be told a viewport to bin over explicitly.

let me know if ive misunderstood you.

**Comment by dmfalke** [comment]
Ah, you're right. The viewport returned above it `0 - 21`. I find this very confusing. Isn't the binning algorithm sensitive to the viewport, so if the client it expanding what it gets back, then the bins might be way smaller than what is desired?

**Comment by dmfalke** [comment]
If the binning is sensitive to viewport, then I will make a new issue for phase 2. Otherwise, we can probably let it go.

**Comment by dmfalke** [comment]
Okay, it sounds like we need an issue for phase 2 to have the client determine the viewport based on variable metadata for histogram visualizations.

**Comment by SheenaTomko** [comment]
Checked malaria treatment start date in India ICEMR Severe and a TAC variable in GEMS1 where binWidth is provided and confirmed that the histogram visualization tool now uses that binWidth by default, even after data subsetting
