### ISSUE TITLE
Study summaries table header updates

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#591]
The header for the study summaries table should say "Study summaries table" and not just "Studies"

![image](https://user-images.githubusercontent.com/25450900/136591659-792da4be-0d3f-44eb-b996-26ab0236bf3b.png)

**Comment by asizemore** [comment]
@danicahelb are you happy with Steve's suggestion of "Studies Summary"?
Also we should get @dpbisme 's opinion because this will change the name in mbio as well.

<img width="1749" alt="Screen Shot 2021-11-09 at 3 28 16 PM" src="https://user-images.githubusercontent.com/11710234/140999707-0c36ed3e-0787-4a6f-b40d-c7cac1592eec.png">

**Comment by asizemore** [comment]
With Danica, decided on "Study Summaries", since it's already clear that what's shown is a table.

<img width="1343" alt="Screen Shot 2021-11-12 at 6 49 08 PM" src="https://user-images.githubusercontent.com/11710234/141596466-af182b16-af83-4679-9a94-9155d1a46682.png">

**Comment by asizemore** [comment]
Closed with EbrcModelCommon [PR #13](https://github.com/VEuPathDB/EbrcModelCommon/pull/13)

**Comment by aaronwlsong** [comment]
The header has been changed as "Studies summaries", closing ticket. 

![image](https://user-images.githubusercontent.com/61077845/142228586-a2543f83-578c-4d86-bf25-a006f6a805ea.png)
