### ISSUE TITLE
Mosaic plot (2x2 & RxC) x-axis value labels need styling fix

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#617]
x-axis labels in mosaic plots have the potential to be squished & illegible (when that value represents a small proportion of the subset)

We will need to redraw the labels, using lines to point the label to the specific area on the axis, in phase 2.

**Comment by asizemore** [comment]
@danicahelb do we have a place we're keeping mockups? I wonder if something like this would be easy to implement + easy to read

<img width="738" alt="Screen Shot 2021-11-18 at 10 01 46 AM" src="https://user-images.githubusercontent.com/11710234/142441765-51b22fbf-6f94-4e21-b615-7a7bb470b8fd.png">

**Comment by asizemore** [comment]
just revisited this ticket since we're talking about mosaic plots today and realized my mockup above is messed up. Here's a better one:

<img width="1422" alt="Screen Shot 2022-09-12 at 11 58 51 AM" src="https://user-images.githubusercontent.com/11710234/189700946-406b8cd4-caea-4849-8eac-9a0aaa1e5391.png">

So the idea is that the x axis labels are all aligned and nicely spaced always. Their little elbowed pointers have the bend located based on the column location. This way the labels stay easy to read, even if the pointer friends get very squished. Additionally note i've put the percentages in the label itself so that it's also clear that for example Kenya is only 0.05% anyways. Just a thought.

**Comment by danicahelb** [comment]
Discussed in 9/12/2022 EDA UX meeting. Folks generally liked @asizemore's mockups above, but suggested moving the X-axis variable label below the elbowed pointers for the x-axis values (ie, in its standard x-axis label position)

To implement the elbowed pointers, we will need to have standard pixels assigned to each value so that the length of the pointers can be calculated. We can give each value a standard number of letters and then use ellipsis to indicate label truncation and hover-over to read the full label

Note, implementation may be difficult / impossible and we may need to revisit how this is handled.

**Comment by danicahelb** [comment]
Discussed in 12/2/22 EDA UX meeting

X-axis value labels currently use ellipses when the label is too long; mouseover will show the full value label

Changes requested:
- [ ] Currently, tooltip only shows up when there are ellipses → change this so that tooltip appears when user mouses over ANY of the value labels
- [ ] X-axis value labels show the percentage, ie (xx%) after the label → move this out of the label and into the tooltip
- [ ] If possible, remove the delay between mousing over the value and the tooltip appearing (Note, Connor indicated that this may be difficult or impossible, but he will look into it…)

**Comment by danicahelb** [comment]
@chowington I made these new tickets for mosaic plots based on other conversations we had in the UX meeting (and one i found while creating the tickets from the UX meeting).

https://github.com/VEuPathDB/EdaNewIssues/issues/491
https://github.com/VEuPathDB/EdaNewIssues/issues/490
https://github.com/VEuPathDB/EdaNewIssues/issues/492

**Comment by danicahelb** [comment]
thanks @chowington. I made this ticket, note it is NOT urgent
https://github.com/VEuPathDB/EdaNewIssues/issues/504
