### ISSUE TITLE
GEMS1A subsetting histogram may not render at very small minimum bin width

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#654]
GEMS1A
Subsetting
Participant repeated measures: Age (months)

If you reduce the binwidth to the minimum 0.062 the spinner seems to spin for ever (I waited a minute or so)

Update: subsetting is [calculating its own min/max allowed values](https://github.com/VEuPathDB/web-eda/blob/main/src/lib/core/components/filter/HistogramFilter.tsx#L789) for the binWidth slider, while the visualization is getting them (more sensible values) from the back-end response.

IIRC the `distribution` endpoint that drives subsetting is stripped down and does not calculate things like this for a reason.

**Comment by chowington** [comment]
This is still happening as of today. @bobular Do you see this as a frontend or backend problem?

**Comment by chowington** [comment]
Our fontend logic calculates the min bin width as the width that would give us 1,000 bins, which is currently far too many for this particular variable endpoint. The smallest bin width for this variable that doesn't cause QA to crash is somewhere around 1, which equates to about 50 bins given this variable's range. I'd hate to force all histograms to have at most 50 bins; ideally we should have a smarter way to calculate the min bin width since it's not currently given to us by the backend for the subsetting histogram. @d-callan Do you have any input on this?

**Comment by bobular** [comment]
Update: in https://github.com/VEuPathDB/web-eda/pull/874 I have added integer-based bin slider constraints.

I don't see any performance problems at minimum bin width (original 1000 bin calculations) with floating point variables, such as GEMS1A -> PRM -> Weight, Height, BMI etc.  Same amount of data (35,187 Participant repeated measures have data for this variable).

**Comment by bobular** [comment]
Resolved by #874

**Comment by sweverschulman** [comment]
In testing this ticket - I noticed there are no performance issues. The bin width is not allowed to go lower than 1. Please @bobular confirm this functionality is correct. If so, we can move this ticket to complete
