### ISSUE TITLE
Visualizations: add "Coming soon" descriptor to greyed out viz tool titles

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#655]
Viz tools that are coming soon (density, heatmap, time series, geolocation) are greyed out in the picker, but the user won't understand why these are not selectable.

Please add "Coming soon!" to the viz tool titles for these 4 tools to indicate that these tools haven't yet been built. 

It should look like: "Density _(Coming soon!)_"

**Comment by chowington** [comment]
Here is what the ticket requests:

![image](https://user-images.githubusercontent.com/12377649/140416351-bd4c4826-b167-435a-94f3-e1881c3cedd7.png)

I think the spacing turned out a little odd. I suggest this instead:

![image](https://user-images.githubusercontent.com/12377649/140416483-46389d4d-1bf8-4d0c-b36f-e8082afe4cfa.png)

@danicahelb Thoughts?

**Comment by chowington** [comment]
@SheenaTomko, how about you?

**Comment by SheenaTomko** [comment]
@chowington , I like the suggestion of moving Coming soon under the name of the plot

**Comment by sweverschulman** [comment]
coming soon viz are currently greyed out

<img width="1005" alt="Screen Shot 2021-11-10 at 10 16 13 AM" src="https://user-images.githubusercontent.com/62298921/141139912-780eab00-7ada-47bc-98e6-c72081601a2a.png">
