### ISSUE TITLE
Bugs in subsetting results data table modal & subset download files

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#656]
- [x] Uncomment button to invoke modal
- [x] Update styling of close button for modal (use an X in the top-right corner)
- [x] Update styling of variable selector toggle (possibilities: change label on state change; add a close icon; or make look even more like a drop-down menu)

QA Tasks (each tagged w/ assignee)
- [x] Incorrect URL is hardcoded for the tabular download (@dmfalke)
- [x] Reflect starred variables in the variable selector drop-down. (@dmfalke)
- [x] Allow user to add/remove starred variables from the selector drop-down. (@dmfalke)
- [x] Have the tree expanded by default in the selector drop-down. (@dmfalke)
- [x] Look into the data loading errors mentioned by Danica. (@dmfalke)
- [x] It would be good to have the featured variables box above the variable selector. (@dmfalke)
- [x] See if we can remove the "select all | clear all | expand all | collapse all" footer to give more real estate to the variable tree. (@dmfalke)
- [ ] When a user is not logged on / does not have an access request approved, they cannot open the subsetting results table. Instead they see the popup instructing them to log in or request access. We had previously talked about enabling users to see 20 rows of data when they don't have access. We should discuss what functionality we'd like during an upcoming ux meeting (@dmfalke)
- [x] Re-position the variable selector window so that it is more obviously a pop-over. (@eikonomega)

**Comment by danicahelb** [comment]
I'm not able to star variables in the variable selector, even though the mouseover says I can

![image](https://user-images.githubusercontent.com/25450900/142665477-afae32f4-9ae3-427b-a4a5-7e9f8d874e69.png)

**Comment by danicahelb** [comment]
it would be good if the columns were sortable (ie, click column header to sort ascending, click again to sort decending)

**Comment by danicahelb** [comment]
when the user opens the variable selector, it would be good to have it expanded by default instead of just seeing this:

![image](https://user-images.githubusercontent.com/25450900/142665968-4f385540-5be6-40a5-b584-9dc925066bcd.png)

**Comment by danicahelb** [comment]
Working with the ELICIT study, filtered Ward = Endamilay. when i clicked "select all", i got this error message

![image](https://user-images.githubusercontent.com/25450900/142666174-6f186e18-78c2-4f05-80f3-c573cf14ce33.png)

**Comment by danicahelb** [comment]
working with GEMS1, filtered subset included cases, 0-11months of age. when I click "select all", columns are NOT added into my table but i didn't get an error message:

![image](https://user-images.githubusercontent.com/25450900/142666832-40a2a712-6f20-4563-98c7-f6cf7b154607.png)

**Comment by danicahelb** [comment]
7. its not obvious that the variable selector is overlaying the table rather than truncating it. could we shift the variable selector a bit up and to the left so that we can see the table under and to the right of the selector?

![image](https://user-images.githubusercontent.com/25450900/142667855-24fcc660-eb78-4f34-8243-530d22352c83.png)

**Comment by danicahelb** [comment]
8. it would be good to have the featured variables box above the variable selector. and i think we can remove the "select all | clear all | expand all | collapse all" footer to give more real estate to the variable tree

![image](https://user-images.githubusercontent.com/25450900/142668998-2b6a1466-69ce-45ce-a486-52a05107946a.png)

**Comment by danicahelb** [comment]
9. when a user is not logged on / does not have an access request approved, they cannot open the subsetting results table. Instead they see the popup instructing them to log in or request access. We had previously talked about enabling users to see 20 rows of data when they don't have access. We should discuss what functionality we'd like during an upcoming ux meeting

**Comment by danicahelb** [comment]
Hi Mike, can you please take a look at the 9 issues I identified above? Thanks!

**Comment by SheenaTomko** [comment]
Reopening to make sure devs can find it

**Comment by eikonomega** [comment]
@SheenaTomko @danicahelb I'll take a look at all the issues here. Thanks!

**Comment by eikonomega** [comment]
> 3. it would be good if the columns were sortable (ie, click column header to sort ascending, click again to sort decending)

Hey @danicahelb I think in the original plan - this was going to be a future addition to the core functionality and not intended for the initial release. I'm thinking we should make this a separate ticket to track from the bug fixes?

**Comment by danicahelb** [comment]
@eikonomega yep, good idea. See https://github.com/VEuPathDB/EdaNewIssues/issues/97

**Comment by SheenaTomko** [comment]
Noticed another issue, if the study name has italics, the html tags are shown rather than italicizing the text
<img width="1122" alt="Screen Shot 2022-02-04 at 1 21 42 PM" src="https://user-images.githubusercontent.com/54597319/152590468-d6b76c7b-7ca3-419b-9b08-1dd729a336c7.png">

**Comment by dmfalke** [comment]
@eikonomega see Sheena's comment above. I think `core-components` should either handle text w/ HTML markup, or better yet, allow the type to be `ReactNode`.

**Comment by dmfalke** [comment]
Pretty much all of the remaining issues have been addressed in the [linked PR](https://github.com/VEuPathDB/web-eda/pull/829). The remaining issue has to do with the behavior a user sees when they do no have access to download the study. Did we ever decide on a UX for this? cc @danicahelb @SheenaTomko

**Comment by danicahelb** [comment]
@dmfalke as discussed in the 2/7/2022 EDA UX meeting, when a user is not logged on / does not have an access request approved, they will not be able to open the subsetting results table. Instead they see the popup instructing them to log in or request access. 

Based on user feedback, we may allow users to view 20 rows of data without having access to the study. But this is not for b56

**Comment by danicahelb** [comment]
**QA results:** 
1. Pass: starred variables are auto-populated as columns in the table in the subset results modal
2. Fail: I can star variables within the modal's variable selector, but when I star terms here, the terms are not added to the results table. Desired behavior: when I star a variable in the modal's variable tree, it should automatically and simultaneously also click the check box to add the variable to the table. _(Note, if I close the subset results modal, the terms starred from within the modal are now starred in the browse/subset variable tree. If I re-open the modal, the term I had originally starred from within the modal now appears in the results table)_
3.

**Comment by danicahelb** [comment]
**Issues to fix (includes items 2 & 7 that failed QA in my comment above, as well as new items identified during latest QA):**

- [ ] When I star terms in the subsetting results modal's variable tree, it should automatically and simultaneously also click the check box to add the variable to the results table. 

- [ ] Please shift the variable selector a bit more down and to the left so we can see that the table extends behind it.

- [ ] When the subsetting results table is large enough that the user needs to scroll down to see the bottom of the table, the left/right scroll bar is cut off from view. Please make this scroll bar always visible (like up/down scroll, which is always visible regardless of what part of the table you are looking at)

**Comment by danicahelb** [comment]
Additional styling changes that can happen post-b56 are documented in https://github.com/VEuPathDB/EdaNewIssues/issues/130

**Comment by danicahelb** [comment]
@dmfalke, via slack:

`When I star terms in the subsetting results modal's variable tree, it should automatically and simultaneously also click the check box to add the variable to the results table.`

I'm not sure I agree with this. I think the act of starring should be separate from adding to the table. I imagine we would not want to remove a variable from the table if it gets unstarred in this view. To me, this is incongruous and might seem like a bug? I'm happy to be overruled if others agree, in which case we should also articulate what happens when a variable is unstarred, and what should happen if the user has intentionally removed starred variables. 

@danicahelb, via slack:
yeah dave, i see your point. perhaps we should disable the ability to star variables from within the subsetting modal variable selector? It is weird to me that I can make the variable appear in the table just by closing the modal and reopening it…

**Comment by SheenaTomko** [comment]
Additional change request:

- [ ] Change the column headers on the table that's created from title case to use the original case that comes from the owl file (for instance, "Observation type" and "Sub-county in Uganda" for the PRISM study)

**Comment by danicahelb** [comment]
Discussed in 2/14/2022 EDA UX meeting. 

We decided that we do NOT want the featured variables or user-starred variables to be added to the subsetting tables by default. It is confusing that the table is automatically populated with featured and starred variables. The default view of the table should just show the relevant ID columns (Participant ID, Household ID, etc). Always minimally showing these IDs will help to indicate to the user that this is a table that can be configured

**Comment by danicahelb** [comment]
@dmfalke Based on 2/14/2022 EDA discussion, these are the remaining to-do items for this ticket:

- [ ] Change the column headers on the table that's created from title case to use the original case that comes from the owl file (for instance, "Observation type" and "Sub-county in Uganda" for the PRISM study)

- [ ] Always show all relevant ID columns (Participant ID, Household ID, etc) even when no variables have been added to the table

- [ ] When just ID columns are in the table (ie, when no variables have been added), please display the text: `To configure this table, click on the "Add columns" button.` above the table (Note that the "Select variables" button is being changed to "Add columns" in this [ticket](https://github.com/VEuPathDB/web-eda/issues/839))

- [ ] Never pre-populate the table with any variables (including featured and starred variables). Default view of the subsetting results table should just show columns for the relevant IDs

- [ ] In https://github.com/VEuPathDB/web-eda/issues/839, we indicate that the "Select variables" button will be moved to the left of the entity name. The variable selector tree should open below this button. Please position the variable selector tree so that we can see the table behind it (We should see the table on top of the variable selector box and also to the left and right of it)

- [ ] When the subsetting results table is large enough that the user needs to scroll down to see the bottom of the table, the left/right scroll bar is cut off from view. Please make this scroll bar always visible (like up/down scroll, which is always visible regardless of what part of the table you are looking at)

- [ ] the name of the downloaded files are all subset.txt. @ryanrdoherty said he intends to name the files {studyId}_{entityId}_subsettedData.txt. Please use more distinct file names

- [ ] If I am in a new analysis and I star one of the featured variables from the browse/subset variable tree, I get an error message when I click "View and download"

**Comment by danicahelb** [comment]
Hi @dmfalke I was talking to mike this morning. We think it is fine to go with this positioning for the variable selector (no need to be able to see the table to the right of the selector). We can revisit this in the future if it is an issue

<img width="390" alt="image" src="https://user-images.githubusercontent.com/25450900/154733203-438cb051-053a-4800-860c-e16afc3cd52a.png">

**Comment by dmfalke** [comment]
>  When the subsetting results table is large enough that the user needs to scroll down to see the bottom of the table, the left/right scroll bar is cut off from view. Please make this scroll bar always visible (like up/down scroll, which is always visible regardless of what part of the table you are looking at)

I'm moving this into a separate issue, since it will likely take some time to address and I'd like to see this one closed :slightly_smiling_face:.

**Comment by dmfalke** [comment]
> Change the column headers on the table that's created from title case to use the original case that comes from the owl file (for instance, "Observation type" and "Sub-county in Uganda" for the PRISM study)

This is being address by @eikonomega in #758

**Comment by danicahelb** [comment]
looks good! thanks dave

**Comment by danicahelb** [comment]
hey @dmfalke when mike pushed his changes, we lost the `To configure this table, click on the "Add columns" button.` text. can you please add it back? You can place it just to the right of the "Add columns" button

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/25450900/155569986-ff401ff3-a43a-4d69-9b48-3f965aa70c73.png">

**Comment by dmfalke** [comment]
Hi @danicahelb. Mike and I struggled to find a way to make this look good without introducing too much noise. I thought maybe it wasn't necessary given that the "Add Columns" button is more prominent. Thoughts?

**Comment by danicahelb** [comment]
yeah, i agree. thanks. closing this now
