### ISSUE TITLE
Sharing: add "share" button and modals for sharing and making public

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#657]
An analysis can be "shared" in two ways
1. It can be made public, in which case it will appear in a public listing
2. An url can be shared with others, without it appearing in a public listing

In both scenarios, we want to educate users on how our sharing model is implemented, and how changes to their analysis will impact what they have shared.

Mock-ups for these scenarios have been carefully developed and reviewed here: https://docs.google.com/presentation/d/1SUhykTuAno5llXA4Z8m8e3_SWJJtsOXFNcZkFDDQNUE/edit?usp=sharing.

The views that will be impacted are
* Analysis page
* **My Analyses** table

- [x] Add the ability to select rows to `DataGrid` component.
- [x] Add the ability to display a checkbox for true/false data in `DataGrid` component.
- [x] Add the ability to update data from a cell in a `DataGrid` component. 
- [x] Add the ability for users to share an individual analysis.
- [x] Indicate on the "My Analyses" page which analyses have been shared/made public.
- [x] Add the ability for users to share an analysis from the "My Analyses" table.
- [x] Coordinate with Dave on how to log in a user.
- [x] You will need to determine if the user is logged in. That can be done with the `useWdkService` hook: `const isLoggedIn = useWdkService(wdkService => wdkService.getUser().then(user => !user.isGuest))`
- [x] The url displayed in the sharing modal requires some and apache redirect. It should be okay to go ahead and hardcode `/analysis/:analysisId`. You can use something like `new URL('/analysis/' + analysis.id, window.location)` to generate the full url.

**Comment by eikonomega** [comment]
@danicahelb All know tasks are finished! I'm ready to meet with whatever team would like to review this. Thanks!

**Comment by sweverschulman** [comment]
@dmfalke @eikonomega is this feature currently available for qa on qa.restricted site?

**Comment by sweverschulman** [comment]
pausing qa until the backend infrastructure is ready for qa on the qa sites

**Comment by sweverschulman** [comment]
Current changes/action items

1.
![image](https://user-images.githubusercontent.com/62298921/148836327-f4bb48bb-eb8a-46b1-afe6-5dee50fc87d8.png)
[ ] Change the upper right hand corner button to 'share analysis' and if there is no share functionality remove/hide button

2. 
![image (1)](https://user-images.githubusercontent.com/62298921/148838895-04eb28fa-a763-4f53-837c-f02e79fe9b6d.png)
 [ ] grey out the submit button if there is no value/typing in the 'unnamed analysis box'
[ ] add the little blue pencil to the 'unnamed analysis box'
[ ] Change language to say: "To make this analysis public, please first give it a name."

3. 
![image (2)](https://user-images.githubusercontent.com/62298921/148839248-d086ac93-9289-49d3-8e7b-6a1c5b1b5b91.png)
[ ]  Change verbiage so that each sentence is its own line/paragraph
[ ] add a link to 'ClinEpiDB Public analysis page' and make it open a new tab

4. Have the client side - create and supply the correct redirect link that users can share.

**Comment by eikonomega** [comment]
This will likely be merged on Friday @danicahelb @SheenaTomko @sweverschulman :)

**Comment by jtlong3rd** [comment]
There is one aspect of this issue that is not yet ready for testing: when you share an analysis, you'll be provided with a "short URL." These short URLs are of the proper form, but won't be functional until [this Systems team Redmine](https://redmine.apidb.org/issues/46574) is complete.

Otherwise, the rest of the sharing feature can (and likely should, in the interest of time) be tested now.

**Comment by sweverschulman** [comment]
On the  'Make analysis public' pop up we would like the warning icon to be placed on i
<img width="64" alt="Screen Shot 2022-02-03 at 4 10 27 PM" src="https://user-images.githubusercontent.com/62298921/152429640-a75a9c58-5461-4f3b-9703-707bbd1907b8.png">
<img width="543" alt="Screen Shot 2022-02-03 at 4 09 52 PM" src="https://user-images.githubusercontent.com/62298921/152429645-9b12a827-59e8-4691-ba8a-59c395aae3b3.png">
t

**Comment by eikonomega** [comment]
I believe that the latest issues raised have been addressed. Moving back into QA.

**Comment by sweverschulman** [comment]
The warning icon now present on the 'Make Analysis Page'

<img width="519" alt="Screen Shot 2022-02-08 at 4 31 37 PM" src="https://user-images.githubusercontent.com/62298921/153079007-2b8234c3-bea5-4e86-aa77-3393c81d4903.png">

**Comment by sweverschulman** [comment]
Sharing Strategies can now be signed off on.
