### ISSUE TITLE
Visualizations: mosaic 2x2 RxC plots should not expect stats table when facet variable is active and showMissingness==true

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#701]
Client needs to be aware of this and the io-ts validators should be lenient
See also
https://github.com/VEuPathDB/plot.data/issues/109

**Comment by bobular** [comment]
@d-callan  - what's the name of the test(s) done for 2x2 and RxC? I think the UI should say what the p-value is from!

**Comment by bobular** [comment]
While fixing this I took an executive decision to move the statistics table into the tabbed area.  This is that it can handle faceting too (when showMissing is not checked).

It now looks like this, when faceting is active
![image](https://user-images.githubusercontent.com/308639/141689548-fc0e6dda-6514-484a-9c58-3fd1a8eeef48.png)

(note that the width isn't correct, but I didn't want to get into layout issues in this PR)

With showMissing toggle on:
![image](https://user-images.githubusercontent.com/308639/141689593-2d043f6f-dfac-469b-9c99-d39bf73a04cf.png)

And with no faceting at all:
![image](https://user-images.githubusercontent.com/308639/141689611-f478e01f-6c12-4895-9617-0d6096eef3a1.png)

**Comment by nkittur-uga** [comment]
This is working well in mosaic rxc plot. 

However, I am unable to QA this right now in mosaic 2x2 plots because of bugs. Both of these were in GEMS1. Faceting in 2x2 is not working for me. Also, if I toggle compatible variables=ON, the list also shows numeric vars which it should not.
<img width="816" alt="Screen Shot 2021-11-17 at 2 44 54 PM" src="https://user-images.githubusercontent.com/67710160/142274456-17867053-e916-4919-9c9d-f467d371b398.png">
<img width="776" alt="Screen Shot 2021-11-17 at 2 46 08 PM" src="https://user-images.githubusercontent.com/67710160/142274459-2f1258b2-e6ff-4ae4-a3cc-932b41d3ee71.png">

**Comment by bobular** [comment]
Thank you @nkittur-uga - I got slightly different error messages on my dev instance but there was definitely a bug which is now fixed.  I'd be grateful if you can test again when it is deployed.

**Comment by nkittur-uga** [comment]
Re-tested and it works as expected in 2x2 table. Statistics are not calculated when the "include no data" option is selected  when facet variable is active and showMissingness==true. QA is complete.
