### ISSUE TITLE
Visualizations - faceted thumbnails should have "X Facets" overlaid in a box with a background

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#716]
Suggestions during the meeting were to have the box at the bottom of the thumbnail - looking a bit like a tab label?

I guess a semi-opaque white background would look good.

**Comment by asizemore** [comment]
<img width="716" alt="Screen Shot 2021-11-17 at 2 24 46 PM" src="https://user-images.githubusercontent.com/11710234/142276873-60a7db31-b8a4-4bef-bb7e-581bc617ae83.png">

Something like the above where the gray goes along the bottom is an option if it's easy? @jtlong3rd I see you've already got a PR for this ticket so if this idea is too late don't worry at all!

**Comment by aaronwlsong** [comment]
Looks good now on qc.website, even though it is neither semi-opaque white background as bobular said, nor the semi-opaque light grey as asizemore showed above. Now it is more like semi-opaque dark grey background with white words. If the semi-opaque white background is not required, I personally think the ticket can be closed, otherwise, it should be changed later.  

![image](https://user-images.githubusercontent.com/61077845/142888109-4e45008c-825b-479d-976b-0f86c52ca28c.png)


![image](https://user-images.githubusercontent.com/61077845/142888587-664b2801-5dfe-41be-94ef-a03dc3bf9e7e.png)
