### ISSUE TITLE
Faceted plot panel doesn't occupy 100% width and have browser's horizontal scroll bar when deployed on QA

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#745]
Works fine in my dev instance, but not on QA.

I don't think screenshots are required ;-)

**Comment by dmfalke** [comment]
The root cause of this has manifested as weird looking layouts if a visualization is loaded when the app first loads in a browser. The cause is multiple versions of material-ui's classname generator (used by `makeStyles`). This is causing classname conflicts since the two versions (ie, instances) have a unique id generator that both start at the same number.

**Comment by nkittur-uga** [comment]
Faceted plot panel now occupies 100% width and browser's horizontal scroll bar. Passes QA.
