### ISSUE TITLE
Update client to use the new hideFrom property.

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/web-eda#801]
the possible values (so far) are 'everywhere', 'downloads' and 'variableTree'

**Comment by jtlong3rd** [comment]
@steve-fischer-200 Something that's come up in my [PR](https://github.com/VEuPathDB/web-eda/pull/808) for this work:

Can `hideFrom` be given to "non-leaf" variables? If so, what is the intended behavior? In my current implementation, if a "non-leaf" variable has a `hideFrom` property, then that variable and all its descendants will be hidden.

**Comment by jtlong3rd** [comment]
Testing ideas:

1. For Amazonia ICEMR Brazil Cohort, the `Settlement` variable has `hideFrom: ["variableTree"]`, so it should appear in the "view and download" modal, but not in the variable trees for the subsetting and visualization tabs
2. For GEMS 1A Case Control, the `Participant ID for matched case` variable has `"hideFrom":["everywhere"]`, so it should appear neither in "view and download" modal, nor in the variable trees for the subsetting and visualization tabs.

**Comment by SheenaTomko** [comment]
Found a bug. 
In PRISM2 border cohort, "Birth date" is supposed to be hidden everywhere. If you search for it as a variable, you can't find it, and if you try to download data, you can't add it as a variable to the file. 

However, if you click on the "Participant" entity in the entity diagram, it takes you to the "Birth date" histogram, presumably because this would be the first variable in the Participant entity if it weren't hidden everywhere.
<img width="1162" alt="Screen Shot 2022-02-02 at 1 36 26 PM" src="https://user-images.githubusercontent.com/54597319/152224316-ceb6f980-8956-4daa-9aca-a483334644e5.png">

**Comment by jtlong3rd** [comment]
Good catch, @SheenaTomko! I investigated, and found that this bug also occurs if the variables are hidden in the "old" way (based on whether `displayType` is `hidden`), and under the same circumstances.

(Clicking on "Participants" in "PRISM2 Border Cohort" also redirect to "Birth date," even though it has `displayType: "hidden"`.)

I'll open (and likely self-assign) an issue describing the deeper bug and what the fix is.

**Comment by SheenaTomko** [comment]
Jamie to open a new ticket specific for the bug, so closing this
