### ISSUE TITLE
Scalability / Performance: Implement message on visualization tools for studies with large amounts of data

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#810]
Making visualizations for studies like UMSP with millions of rows of data can still take ~30 sec once parameters have been selected. Since this is enough time for people to wonder if something has gone wrong, we want to add a message that says something like "This visualization may take up to 1 minute to appear due to the large amount of data being used."

Steve noted that we may not be able to infer which studies will require this message, so we may want to create a prop in the presenters that controls whether the message appears for all visualization tools for a given study. 

This is needed for b56.

**Comment by danicahelb** [comment]
ClinEpi team to review performance issues, potentially move to b57

**Comment by danicahelb** [comment]
Visualizations with larger studies are slow. Talked with Steve today; a proper fix will require significant engineering on the backend. since we will fix this properly in the future, we won't add an annotation property to indicate which studies have slow performance.

In the meantime, we will implement a hack. If the study is MAL-ED, Amazonia Peru, or UMSP, put up a flag to let the user know that visualizations may be slow.

"Visualizations may take up to 1 minute to appear due to the large amount of data in this study."

**Comment by SAK22** [comment]
Looks good in MAL-ED and Amazonia Peru
