### ISSUE TITLE
Downloads: Allow mark-up in study displayName in subset table modal

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#831]
See @SheenaTomko's comment here: https://github.com/VEuPathDB/web-eda/issues/656#issuecomment-1030283076. It would be great if `core-component` React components would allow the type `ReactNode` for `text`, rather than just `string`.

**Comment by bobular** [comment]
I'm currently assessing if I can do this (including the `core-components` bit)

**Comment by bobular** [comment]
Yes, it looks like I can take this one. I will just do it for the `Header` components, @eikonomega - it looks like buttons and chips also have a `text: string` prop - but I won't touch those until advised further.

Just for the record, you can test this without any special data access permissions using **ICEMR Severe P falciparum and vivax Cohort** study

![image](https://user-images.githubusercontent.com/308639/153412627-ad383ef6-6a15-4183-bc38-521a3f5c3f27.png)

PS Michael - that screenshot was done within Firefox and it seems to have worked (there's an [old ticket](https://github.com/VEuPathDB/core-components/issues/12) that suggests otherwise)

**Comment by bobular** [comment]
Should be good now :+1: 
Thanks to @eikonomega for the components side (I gave valuable support...)
![image](https://user-images.githubusercontent.com/308639/153494755-497f18e8-eb41-4795-858c-fa7412ed7dce.png)

**Comment by nkittur-uga** [comment]
Fixed. QA is complete.
