### ISSUE TITLE
Styling updates for subsetting results modal

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#935]
Post b56, consider: 

1. Should the variable tree (selector) always be shown open on the left side of the modal (to mimic the styling on the Browse & subset tab)?

2. If the variable tree is shown open on the left side of the modal by default, should the tree be collapsable to give more real estate to the table?

3. Should the variable tree be expanded by default to show all variables? or just all parents & sub-parents? or just entities?

Edit (Connor): See [Dave's comment below](https://github.com/VEuPathDB/web-eda/issues/935#issuecomment-1123141782) for the final reqs for this ticket

**Comment by danicahelb** [comment]
discussed in 3/21/2022 EDA UX meeting. @danicahelb will make mockups based on feedback from the meeting:

**In the subsetting results download modal:**

1. Make it look more like a table that the user needs to configure: 4 ghost columns vs 1 single ghost column. Perhaps add a gear icon to the ghost column headers?
2. Change the “Add columns” text to “Build the table” 
3. Try out having the variable tree (with check boxes to select / deselect variables) open on the left by default, and putting text between the Entity numbers and the tree / table that says “Build a table to download” (in this option, the “Add columns” button would be removed)
4. If the variable tree is shown open on the left side of the modal by default, should the tree be collapsable to give more real estate to the table?
5. Should the variable tree be expanded by default to show all variables? or just all parents & sub-parents? or just entities?
6. “X” icons in column headers to delete those columns?

**On the download tab:**
1. Update the text under “My subset” to be more user friendly
2. Somehow indicate that rows come from subsetted data, columns are what you are selecting

**Comment by danicahelb** [comment]
Discussed in 4/25/2022 EDA UX meeting.

We debated having 3 step vs 2 step process, and decided to stick to 2 step for now

Mockups were approved, and now require updates from styling team. Assigning to @asizemore

**Comment by dmfalke** [comment]
I'm giving this issue a high cost, given the substantial number of changes. We should get someone working on this asap, so that it can be ready for b58.

As I understand the latest mock-ups, these are the necessary changes:
- [ ] New 2-column layout, with headings
- [ ] Create "cartoon" table graphic
- [ ] Show "cartoon" table when no non-required columns have been selected
- [ ] Add **Required columns** section above variable tree
- [ ] Add **lock** and **remove** icons to table column heading cells
- [ ] Allow table to be horizontally (and vertically?) scrolled, independent of controls that are below the table
- [ ] Allow table to be expanded, which will replace the 2-column layout, including headings

We will also need to give the clinepi team a way to declare which additional columns are required. This could be done in the presenters file and added as a new dataset record table attribute. The client can then request this table from the WDK REST service. This should probably be in a separate issue.

**Comment by danicahelb** [comment]
We will still want the same primary and foreign keys as is currently in each of the subsetting tables for each entity. 

The only additional column(s) will always be annotated in the owl file. the annotation property is `"mergeKey" = yes`

**Comment by dmfalke** [comment]
Thanks, @danicahelb. I updated my comment above.

**Comment by danicahelb** [comment]
I'm moving this ticket to complete. I documented all issues that I identified during QA in this ticket: https://github.com/VEuPathDB/web-eda/issues/1169

**Comment by danicahelb** [comment]
Looks good now, thanks @chowington!
