### ISSUE TITLE
Add early variable tree validation to prevent confusing error messages

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-eda#943]
When an entity does not have any variables, the following error is thrown:
https://github.com/VEuPathDB/web-eda/blob/b1a346e330e1e72f0dc8e0dfd6feda33992d6fce/src/lib/workspace/Utils.ts#L30-L32

This is a little bit misleading, since the entity does exist in the data, but it is excluded from the `fieldTree`. We should add some early validation and throw an error if an entity has no variables. This could potentially be done here:
https://github.com/VEuPathDB/web-eda/blob/b1a346e330e1e72f0dc8e0dfd6feda33992d6fce/src/lib/core/api/SubsettingClient/index.ts#L36-L47.

It might also be possible to encode this in the `io-ts` type [[see this](https://github.com/gcanti/io-ts/blob/master/index.md#branded-types--refinements)]:
https://github.com/VEuPathDB/web-eda/blob/b1a346e330e1e72f0dc8e0dfd6feda33992d6fce/src/lib/core/types/study.ts#L198

```typescript
// a unique brand for non-empty arrays
interface NonEmptyBrand {
  readonly NonEmpty: unique symbol // use `unique symbol` here to ensure uniqueness across modules / packages
}

const NonEmpty = t.brand(
  t.array, // a codec representing the type to be refined
  (n): n is t.Branded<Array|string, NonEmptyBrand> => n.length > 0, // a custom type guard using the build-in helper `Branded`
  'NonEmpty' // the name must match the readonly field in the brand
)

type NonEmpty = t.TypeOf<typeof NonEmpty>

const NonEmptyArray = t.intersection([t.array, NonEmpty])
```

**Comment by jernestmyers** [comment]
I'm putting a pause on this issue for now because I've yet to find a viable solution. But I wanted to document some things for future reference.

First, the following block of code circumvents the call to `getStudyMetadata` for `prerelease` studies. Without this early return, a `500 Internal Server Error` is thrown that states `Found no entities for study: <study name>`.
https://github.com/VEuPathDB/web-eda/blob/1993d87edd50753d9c94a699b67ae1b2298e1573/src/lib/core/hooks/study.ts#L185-L206

But in circumventing that error message, we instead invoke `findFirstVariable` in the `DefaultVariableRedirect` and `WorkspaceContainer` components, which throws the misleading error message mentioned at the top of this issue:
https://github.com/VEuPathDB/web-eda/blob/1993d87edd50753d9c94a699b67ae1b2298e1573/src/lib/workspace/DefaultVariableRedirect.tsx#L26-L38
https://github.com/VEuPathDB/web-eda/blob/1993d87edd50753d9c94a699b67ae1b2298e1573/src/lib/workspace/WorkspaceContainer.tsx#L51-L70

Possible ideas could be:
- Remove guards from `useStudyMetadata` for `prerelease` studies and let those without server data error out; at least in this case, the error message would feel more accurate
- Block the calls to `findFirstVariable` in the event the data is stubbed out
- Have the backend include sufficient enough data to execute the `getStudyMetadata` call and then do error handling within the `transformResponse` portion of the method, like `r.study.rootEntity.variables.length ? <do this> : <throwError>`

**Comment by dmfalke** [comment]
In reviewing this issue with @jernestmyers, we realized that my original suggestion was incomplete, since arrays are generic. I think we should just use https://gcanti.github.io/io-ts-types/. There are several useful types in the library, including this one.

**Comment by SheenaTomko** [comment]
No easy way to qa this. Marking as complete.
