### ISSUE TITLE
Scatterplot: y axis range changes when smoothed mean shown

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#95]
In toggling between raw data or BestFitLineWithRaw, the y-axis range changes little if it all. However, when selecting smoothedMean or smoothedMeanWithRaw, the y-axis range changes drastically. 

Example:
Data: SCORE
Subset: none
Plot: scatter
x-axis: age at enrollment
y-axis: birth year

Here the y-axis changes from (1930, 2010) to (0, 2010) (approximately).

**Comment by moontrip** [comment]
Hi @asizemore and @dmfalke 

In summary, I tentatively conclude that it is a bug at plotly, thus I have implemented something to address this issue, which would work fine, I suppose.

For more details: I have tested this example and several other datasets (with different variables). Note that I have been relying on plotly's autorange feature for y-axis as I was reluctant to set the range manually: it was because several plots were involved in there (like raw data markers, smoothed mean line, confidence interval (bounds), and best fit line). Somehow, for the specific dataset that Ann noticed, the plotly's autorange did not work correctly. To overcome the issue, I have decided to manually set y-axis range. As a result, it shows reasonable plot now: screenshot is attached for the case of smoothedMeanWithRaw with the example above.

@asizemore Please note that it would take some time for this change to be reflected to the feature site as it needs [review/merge](https://github.com/VEuPathDB/web-eda/pull/93) and updating to the feature site. Please feel free to ask me if you find another issue concerning the scatter plot viz.

![scatter-new1](https://user-images.githubusercontent.com/12802305/119392992-6e850c80-bc9e-11eb-847b-e3a3b2943c9a.png)

**Comment by asizemore** [comment]
Thanks so much @moontrip!! The new plot looks great. 
Thank you for the detail about plotly as well -- I understand the underlying problem much better. I agree it makes sense to use plotly's autorange in general, and I find the way plotly's autorange failed with the multiple plots very interesting. 
Thanks again for looking into this!
