### ISSUE TITLE
Visualizations: Line plot front end does not handle ordinal x-vars

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#963]
Ordinal x-vars, such as "Age group" `["0-11 months", "12-23 months", "24-59 months"]` currently break the front end.

If we support these (which I guess we will) it may make x-axis zooming controls more complicated (heads up to @moontrip) - unless we decide not to have zooming controls on x.

UPDATE: date variables on the y-axis were causing a 500 on the back end, but we decided not to calculate error bars for date variables, and so the PR for this ticket also disables error bars for date y-variables.

NOTE for testers: The only ordinal variable (there are very few) that seems to require reordering is "Age group" from SCORE Seasonal Transmission S. haematobium Cluster Randomized Trial

**Comment by moontrip** [comment]
@bobular My two cents: yeah, we can't support that case in the axis control. Not quite sure whether we will have X-axis control for Lineplot Viz, but if we have, then we may check the case Number, Date, Ordinal etc. to show/hide X-axis range control.

**Comment by aaronwlsong** [comment]
It seems that the issue still exists among certain type of y-axis variables when x-axis is set up as ordinal var such as "age group". 

Basically, when x-axis use "age group",  and  for y-axis:
Looks good now; 
1.  Continuous vars: such as "respiratory rate", "age", etc.  (see pic 1 and 2)
2. For date type vars:  (see pic 5 and pic 6)

"500 error " happens ;
1. For categorical type vars such as "study timepoint", "Diarrhea in past two weeks",:   (see pic 3 and 4)

Pic 1 in GEMS 1 Case control study
<img width="1521" alt="Screen Shot 2022-03-18 at 11 28 15 AM" src="https://user-images.githubusercontent.com/61077845/159035351-5dfa3e54-0903-4e2d-8fe9-15b9952296ba.png">

Pic 2 in GEMS1A HUAS Lite Survey
<img width="1339" alt="Screen Shot 2022-03-18 at 11 34 01 AM" src="https://user-images.githubusercontent.com/61077845/159035370-c407f3d6-844f-42cb-bbdb-6ed69409eaf6.png">

Pic 3 in GEMS 1 Case control study
<img width="1771" alt="Screen Shot 2022-03-18 at 11 51 00 AM" src="https://user-images.githubusercontent.com/61077845/159036956-524cc3d8-8de8-4481-9101-18cfde18c8e4.png">

Pic 4 in GEMS1A HUAS Lite Survey
<img width="1421" alt="Screen Shot 2022-03-18 at 11 27 48 AM" src="https://user-images.githubusercontent.com/61077845/159036038-42a137a1-a861-4cb3-bef3-70cafc172f72.png">

Pic5 in GEMS1A HUAS Lite Survey
<img width="1485" alt="Screen Shot 2022-03-18 at 11 54 30 AM" src="https://user-images.githubusercontent.com/61077845/159037447-e50cfdb0-30c7-47b3-b535-67f8c6269c95.png">

Pic 6  in GEMS 1 Case control study
<img width="1485" alt="Screen Shot 2022-03-18 at 11 54 30 AM" src="https://user-images.githubusercontent.com/61077845/159037552-1267d516-c17e-4067-a079-09cbe87bea51.png">

**Comment by danicahelb** [comment]
for LLINEUP, study timepoint cannot be selected for the x-axis.
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/25450900/159809146-315fdf6c-f74b-4d0b-a5d2-27e30a3676e8.png">

I checked the value map and LLINEUP is correctly annotated as ordinal with "displayOrder". LLINEUP is also annotated as is_temporal = yes in the conversion file

**Comment by danicahelb** [comment]
@aaronwlsong you were getting the 500 error when trying to plot categorical data on the y-axis. this is not yet working, but will be fixed in https://github.com/VEuPathDB/web-eda/issues/956

**Comment by bobular** [comment]
Regarding the x-axis variable and the comment 3 in https://github.com/VEuPathDB/web-eda/issues/825#issuecomment-1076912300 

Currently allowed dataShapes are `ordinal` and `continuous` - that is the only constraint.

LLINE-UP Study timepoint is `categorical`.  The `isTemporal` is not taken into consideration by lineplot constraints.  We'll either need to change the constraints (and potential front end work to make sure it still works) or change the annotations.  

For comparison, GEMS1 Age group is working as a x-axis variable (it's shape is `ordinal`)

@danicahelb

**Comment by d-callan** [comment]
idk that setting the display order is the same as making a string ordinal? is the proposal that this should be the case bc id be hesitant of that...

**Comment by danicahelb** [comment]
Had a call with @d-callan @jaycolin and @SheenaTomko 

We decided that Jay will patch the database so that any term where valueOrder has been annotated in the valueMap will have dataShape = ordinal.

From [SOP 2.06](https://docs.google.com/document/d/1iW-slJzSHDGe3Ws3KPjc2UJtvEDc37_kR-x1juxr2aM/edit):

_**valueOrder**: Populate with "1", "2", "3", etc to have the values show up in a certain order on the website. Fill this out for ALL ordinal variables (even when alphabetical order would place the values in the correct order), so that ordinality can be inferred by the data dev team. Leave blank for all non-ordinal variables._

**Comment by danicahelb** [comment]
@jaycolin fixed the issue with categorical/ordinal data shape for all studies.

I tested with LLINEUP, using "Study timepoint" on the x-axis. I was able to select this variable now, but it gives a 500 error:


<img width="1422" alt="image" src="https://user-images.githubusercontent.com/25450900/162336848-64dac5a0-5354-4d7d-92da-6d26994d4021.png">

**Comment by danicahelb** [comment]
We're waiting on fixes to https://github.com/VEuPathDB/EdaLoadingIssues/issues/28. I'm moving this ticket to "Ready for testing" and adding a pause label

**Comment by danicahelb** [comment]
One issue I'm finding is that not all variables that have the valueOrder annotated are able to be selected for the x-axis in line plots.

For example, I'm looking at SCORE S. mansoni cluster randomized trial. "Village study timepoint" (provider label village_study_year), "Village study arm" (provider label study_arm), and "Study timepoint" (provider label study_arm) all have valueOrder annotated in the valueMap file. The valueMap file was last updated on Feb 15, 2022.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/25450900/163282767-74754666-c01b-4dc1-8b28-39ff3eb43aa0.png">

Because valueOrder has been filled out, I would expect these all to have dataShape = ordinal and all be able to be used on the x-axis of the line plot. However, only "Village study arm" can be selected for the x-axis.

<img width="622" alt="image" src="https://user-images.githubusercontent.com/25450900/163282851-2566d28c-1083-43bb-8ceb-69976a59e579.png">

@nkittur-uga can you confirm that the valueMap file in the score_sm_crt folder is the correct value map for this study?
@bobular can you confirm that dataShape is categorical for "Village study timepoint" and "Study timepoint" but ordinal for "Village study arm"?

**Comment by nkittur-uga** [comment]
@danicahelb Yes, that is the correct folder.

**Comment by moontrip** [comment]
@danicahelb I could check your question to @bobular. Yes, you are correct: 
"Village study timepoint" and "Study timepoint" = categorical 
"Village study arm" = ordinal

**Comment by SheenaTomko** [comment]
@jaycolin please take a look

**Comment by jaycolin** [comment]
Audited all studies, patched every instance I could find where the valueMap.txt ordinality was missing or wrong

**Comment by danicahelb** [comment]
looks good now, thanks everyone!
